#!/bin/bash
source /etc/default/dynamic-motd
UNAME_R=$(uname -r)
UNAME_V=$(uname -v | sed 's/ SMP//g' | sed 's/ PREEMPT//g')
UNAME_M=$(uname -m)
# Ubuntu
if [[ -f "/etc/lsb-release" ]]; then
	[ -r /etc/lsb-release ] && . /etc/lsb-release
	if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
		# Fall back to using the very slow lsb_release utility
		DISTRIB_DESCRIPTION=$(lsb_release -s -d)
	fi
	HEADER=$(printf "%s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$UNAME_R" "$UNAME_V" "$UNAME_M")
	figlet ${H_POS} -f term $HEADER
else
	# Debian / Devuan
	if [[ -f "/etc/os-release" ]]; then
		[ -r /etc/os-release ] && . /etc/os-release
		if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
			# Fall back to using the very slow lsb_release utility
			DISTRIB_DESCRIPTION=$(lsb_release -s -d)
		fi
		HEADER=$(printf "%s %s %s %s\n" "$DISTRIB_DESCRIPTION" "$UNAME_R" "$UNAME_V" "$UNAME_M")
		figlet ${H_POS} -f term $HEADER
	else
		uname -snrvm
	fi
fi
