#!/bin/bash
source /etc/opt/board.txt
source /etc/default/dynamic-motd

if [[ "$BRANDING" == "true" ]]; then
	echo "";
	toilet -f ${T_FONT} --filter ${T_FILTER} $MOTD;
	echo "";
else
	if [[ -f "/proc/device-tree/model" ]]; then
		MODEL=$(tr -d '\0' </proc/device-tree/model)
		BLD="\033[1m"
		FIN="\033[0m"
		echo -e "${BLD}";
		figlet ${B_POS} -f term $MODEL;
		echo -e "${FIN}";
	fi
fi
