#!/bin/bash
temp=$(/opt/vc/bin/vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
COL="\033[1m"
FIN="\033[0m"
echo -e "${COL}CPU Temp:${FIN} " $temp°C
echo -e "${COL}Cores:${FIN}    " $(sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq)
echo -e "${COL}Governor:${FIN} " $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo -e "${COL}Uptime:${FIN}   " $(uptime)
