#!/bin/bash
temp=$(/opt/vc/bin/vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
CPU=`lscpu | grep "Model name" | sed -n 1p | sed 's/Model name://g' | sed -r '1s/\s+//g'`
CPUM=`lscpu | grep "CPU max MHz" | sed -n 1p | sed 's/CPU max MHz://g' | sed -r '1s/\s+//g' | sed 's/.0000//g'`
COL="\033[1m"
FIN="\033[0m"
echo -e "${COL}== DISK USAGE${FIN}"
df -h | egrep '(Filesystem)|(/dev/mmc)|(/dev/root)|(/dev/sd)|(/dev/nvme)'
echo ""
echo -e "${COL}== SYSTEM STATUS${FIN}"
echo -e "${COL}Temperature:${FIN}" $temp°C
if [[ -f "/sys/devices/system/cpu/present" ]]; then
	echo -en "${COL}Processor${FIN}:  " $CPU; echo -en " ("$CPUM; echo -e " MHz)";
else
	echo -e "${COL}Cores:${FIN}      " $(sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq);
fi
echo -e "${COL}Governor:${FIN}   " $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo -e "${COL}Memory:${FIN}     " $(grep MemTotal /proc/meminfo | sed 's/MemTotal:        //g')
echo -e "${COL}Entropy:${FIN}    " $(cat /proc/sys/kernel/random/entropy_avail)
echo -e "${COL}Uptime:${FIN}     " $(uptime)
