#!/bin/bash

if [ -f /etc/default/dynamic-motd ]; then
	source /etc/default/dynamic-motd;
	if [[ "$MENUCONFIG" == "true" ]]; then
		# menu-config
		echo "";
		echo -e "To configure your Raspberry Pi run 'menu-config'";
		# run once and disable
		sed -i 's/MENUCONFIG="true"/MENUCONFIG="false"/g' /etc/default/dynamic-motd;
	fi
fi
