#!/bin/bash

initrd_efi="/boot/efi/initrd.gz"
initrd_boot="/boot/initrd.gz"

echo "Creating initrd.gz."
rm -fr /boot/{initrd.gz,initrd.img-*-bak}
rm -fr /boot/efi/{initrd.gz,initrd.img-*-bak}
cp -f /boot/initrd.img-* ${initrd_boot}
cp -f /boot/initrd.img-* ${initrd_efi}
