#!/bin/bash
# activity led switch

rpi_switch () {
sh -c 'echo 0 > /sys/devices/platform/leds/leds/led0/brightness'
}

ml_switch () {
sh -c 'echo 0 > /sys/devices/platform/leds/leds/ACT/brightness'
}

rpi_switch > /dev/null 2>&1
#ml_switch > /dev/null 2>&1
