#!/bin/bash
# power led switch

rpi_switch () {
sh -c 'echo 0 > /sys/devices/platform/leds/leds/led1/brightness'
}

ml_switch () {
sh -c 'echo 0 > /sys/devices/platform/leds/leds/PWR/brightness'
}

rpi_switch > /dev/null 2>&1
#ml_switch > /dev/null 2>&1
