#!/bin/bash
COL="\033[1m"
FIN="\033[0m"

echo -e "${COL}Running System Setup${FIN} ..."
sleep 1s
sudo dpkg-reconfigure locales tzdata keyboard-configuration
sleep 1s
if [ -e /etc/new.motd ]; then
	sudo rm -f /etc/motd
	sudo mv -f /etc/new.motd /etc/motd;
else
	:;
fi
sleep 1s
sudo update-ca-certificates -f
echo ""
echo -e "${COL}System is ready to go${FIN}."
sudo rm -f /usr/local/bin/run-setup
