#!/bin/bash

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
fi
if [[ -f "/etc/os-release" ]]; then
	NAME=`cat /etc/os-release | grep -w NAME | sed 's/NAME=//g' | sed 's/"//g' | sed 's/ GNU\/Linux//g'`
else
	NAME="none"
fi

if [ $# -eq 0 ]; then
	echo -e "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "rh" OPTION; do
	case $OPTION in
		r)
			echo ""
			echo -e "Running System Setup ..."
			sleep .75
			sudo dpkg-reconfigure locales tzdata keyboard-configuration
			sleep .50
			if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
				if [[ "$NAME" == "Ubuntu" ]]; then echo ""; fi
				echo "Reconfiguring debconf ..."
				if [[ `command -v tasksel` ]]; then
					:;
				else
					sudo apt update
					sudo apt install -y tasksel
				fi
				sleep .75
				sudo apt-get update
				sudo apt-get install --reinstall debconf
				sudo dpkg-reconfigure tasksel
				echo "Done."
				echo ""
			fi
			sleep .50
			sudo update-ca-certificates -f
			echo ""
			echo -e "Setup complete."
			exit 0
			;;
		h)
			echo ""
			echo -e "	-r	Run setup"
			echo ""
			exit 0
			;;
	esac
done

exit 0
