#!/bin/bash
# RASPBERRY PI IMAGE BUILDER
# SYSTEM MENU INTERFACE
if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
	whiptail --msgbox "    Your board is not supported." 0 0
	exit 0
fi

# functions
change_password(){
while true; do
	export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray';
	PASSWD1=$(whiptail --backtitle "Menu Interface: User Password" --title "User: $USER" --passwordbox "Enter new password" --nocancel 8 78 3>&1 1>&2 2>&3)
	PASSWD2=$(whiptail --backtitle "Menu Interface: User Password" --title "User: $USER" --passwordbox "Enter new password (again)" --nocancel 8 78 3>&1 1>&2 2>&3)
	if [ "$PASSWD1" = "$PASSWD2" ]; then
		PASSWORD="${PASSWD1}"
		export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
		if (whiptail --backtitle "Menu Interface: User Password: Confirm" --title "Confirm" --yesno "    Set the new password?" 0 0); then
			echo "$PASSWORD" | sed 's/.*/\0\n\0/' | sudo passwd -q $USER 2> /dev/null
			whiptail --backtitle "Menu Interface: User Password: Confirmation" --title "Confirmation" --msgbox "    Password changed successfully." 0 0
		else
			whiptail --title "Cancelled" --msgbox "    Hit enter to return to menu." 0 0
		fi
	else
		export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
		whiptail --backtitle "" --msgbox "    Passwords don't match? Try again." 0 0
		continue
	fi
	break
	clear -x
done
}

change_hostname(){
CURRENT=`hostname`
export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
NEWHOST=$(whiptail --backtitle "Menu Interface: Hostname" --title "Current: $CURRENT" --inputbox "Enter new hostname" --nocancel 8 78 3>&1 1>&2 2>&3)
HOSTNAME="${NEWHOST}"
export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
if (whiptail --backtitle "Hostname: Confirm" --title "Confirm" --yesno "    Apply new hostname? ${HOSTNAME}" 0 0); then
	sudo sh -c "echo '$HOSTNAME' > /etc/hostname"
	sudo sed -i "2s/.*/127.0.1.1	$HOSTNAME/" /etc/hosts
	if [[ `grep -w "Devuan" "/etc/os-release"` ]]; then
		sudo service hostname.sh --full-restart
		sudo service avahi-daemon restart
	else
		sudo hostnamectl set-hostname $HOSTNAME
		sudo systemctl restart avahi-daemon
	fi
	whiptail --backtitle "Hostname: Confirmation" --title "Confirmation" --msgbox "    ${HOSTNAME} applied successfully." 0 0
else
	whiptail --title "Cancelled" --msgbox "    Hit enter to return to menu." 0 0
fi
clear -x
}

clear -x
BANNER="Menu Interface: "
SYS="System "
SET="Settings"

# main menu
while [ 1 ]
do
CHOICE=$(
export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
whiptail --backtitle "$BANNER$SYS$SET" --title "System Menu Config" --menu "" --nocancel 0 25 0 \
	"W)" "Wireless          Configure wireless network interface" \
	"" "" \
	"1)" "Password          Change the default user password" \
	"2)" "Hostname          Change the default hostname" \
	"3)" "Keyboard          Change keyboard layout" \
	"4)" "Locales           Change language settings" \
	"5)" "Timezone          Change regional settings" \
	"6)" "Governor          Dynamic frequency scaling" \
	"" "" \
	"U)" "Update            Menu interface configuration tool" \
	"Q)" "Quit .." 3>&2 2>&1 1>&3
)
case $CHOICE in
	"W)")
		if [[ `command -v nmtui` ]]; then
			sudo nmtui
		else
			swh -m
		fi
		;;
	"")
		;;
	"1)")
		change_password
		;;
	"2)")
		change_hostname
		;;
	"3)")
		sudo dpkg-reconfigure keyboard-configuration
		;;
	"4)")
		sudo dpkg-reconfigure locales
		;;
	"5)")
		sudo dpkg-reconfigure tzdata
		;;
	"6)")
		governor -m
		;;
	"")
		;;
	"U)")
		MENUDIR="/usr/local/bin"
		if [[ `command -v menu-config-update` ]]; then
			sudo mv -f ${MENUDIR}/menu-config-update ${MENUDIR}/menu-config-update.orig
		fi
		sudo wget -cq https://raw.githubusercontent.com/pyavitz/rpi-img-builder/menuconfig/menu-config-update -P ${MENUDIR}/
		sleep .50
		sudo chmod +x $(command -v menu-config-update)
		if [[ `command -v menu-config-update` ]]; then
			sudo rm -f ${MENUDIR}/menu-config-update.orig
		else
			sudo mv -f ${MENUDIR}/menu-config-update.orig ${MENUDIR}/menu-config-update
		fi
		menu-config-update
		exit 0
		;;
	"Q)")
		clear -x
		exit 0
		;;
	esac
done
