#!/bin/bash

# STAGE 1
stable_sources(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://deb.debian.org/debian ${DISTRO_VERSION} main contrib non-free
deb http://deb.debian.org/debian ${DISTRO_VERSION}-updates main contrib non-free
deb http://deb.debian.org/debian ${DISTRO_VERSION}-proposed-updates main contrib non-free
deb http://deb.debian.org/debian-security ${DISTRO_VERSION}-security main contrib non-free
deb http://deb.debian.org/debian ${DISTRO_VERSION}-backports main contrib non-free
EOF
}

unstable_sources(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://deb.debian.org/debian ${DISTRO_VERSION} main contrib non-free
EOF
}

distro_release(){
if [[ "$DISTRO_VERSION" == "bullseye" ]]; then
	stable_sources;
else
	unstable_sources;
fi
}

# STAGE 2
network_setup(){
rm -f /etc/network/interfaces
mv -f credentials.txt /boot/rename_to_credentials.txt
cp -f board.txt /etc/opt/
ln -sr /etc/opt/board.txt /etc/opt/soc.txt
chown root:root /etc/opt/board.txt

tee /etc/opt/interfaces.manual <<EOF
### Interfaces
source /etc/network/interfaces.d/*

### Loopback network interface
auto lo
iface lo inet loopback

### Ethernet
allow-hotplug eth0
iface eth0 inet dhcp
    #address 10.0.0.10
    #netmask 255.255.255.0
    #gateway 10.0.0.1
    #dns-nameservers 8.8.8.8 8.8.4.4

### Mobile tether
#allow-hotplug usb0
#iface usb0 inet dhcp

### Wifi
allow-hotplug wlan0
iface wlan0 inet dhcp
	wireless-power off
	#address 10.0.0.10
	#netmask 255.255.255.0
	#gateway 10.0.0.1
	#dns-nameservers 8.8.8.8 8.8.4.4
	wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

EOF

tee /etc/opt/interfaces <<EOF
### Interfaces
source /etc/network/interfaces.d/*

### Loopback network interface
auto lo
iface lo inet loopback

### Ethernet
allow-hotplug eth0
iface eth0 inet dhcp
    #address 10.0.0.10
    #netmask 255.255.255.0
    #gateway 10.0.0.1
    #dns-nameservers 8.8.8.8 8.8.4.4

### Mobile tether
#allow-hotplug usb0
#iface usb0 inet dhcp

### Wifi
allow-hotplug wlan0
iface wlan0 inet dhcp
	wireless-power off
	wlan_address 10.0.0.10
	wlan_netmask 255.255.255.0
	wlan_gateway 10.0.0.1
	wlan_dns-nameservers 8.8.8.8 8.8.4.4
	wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

EOF

tee /etc/opt/wpa_supplicant.manual <<EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
	ssid="mywifissid"
	scan_ssid=1
	key_mgmt=WPA-PSK
	psk="wifipasskey"
}
EOF

tee /etc/opt/wpa_supplicant.conf <<EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=

network={
	name=
	scan_ssid=1
	key_mgmt=WPA-PSK
	password=
}
EOF

}
