#!/bin/bash

# COLORS
RED="\e[0;31m"
GRN="\e[0;32m"
PNK="\e[0;35m"
YLW="\e[0;36m"
WHT="\033[0m"
FIN="\e[0m"

# ECHOES
echo_extract(){
echo -e "${WHT}Extracting archive${FIN} ..."
}

echo_compress(){
echo -e "${WHT}Compressing image${FIN} ..."
}

echo_shrink(){
echo -e "${WHT}Shrinking image${FIN} ..."
}

echo_patch(){
echo -e "${WHT}Applying patches${FIN} ..."
}

echo_done(){
echo -e "${WHT}Done${FIN}."
}

echo_ok(){
echo -e "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_nok(){
echo -e -n "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_fail(){
echo -n -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
}

echo_bdone(){
echo -e "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
}

echo_kernel(){
echo -e "${WHT}Downloading ${KERNEL}-${VERSION}${FIN} ..."
}

echo_firm(){
echo -e "${WHT}Downloading firmware${FIN} ..."
}

echo_stable(){
echo -e "${WHT}Downloading stable linux${FIN} ..."
}

echo_mainline(){
echo -e "${WHT}Downloading mainline linux${FIN} ..."
}

echo_cconfig(){
echo -e "${WHT}Making ${MYCONFIG}${FIN} ..."
}

echo_fconfig(){
echo -e "${WHT}Making foundation defconfig${FIN} ..."
}

echo_bconfig(){
echo -e "${WHT}Making builder defconfig${FIN} ..."
}

echo_menuconfig(){
echo -e "${WHT}Opening menuconfig${FIN} ..."
}

echo_build(){
echo -e "${WHT}--- Building deb packages${FIN} ..."
}
