#!/bin/bash

edit_defconfig(){
# module sig
if [[ `grep -w "CONFIG_MODULE_SIG=y" "arch/${ARCH}/configs/${LINUX_DEFCONFIG}"` ]]; then
	:;
else
	echo "CONFIG_MODULE_SIG=y" >> arch/${ARCH}/configs/${LINUX_DEFCONFIG};
fi
# cifs posix
if [[ `grep -w "CONFIG_CIFS_POSIX=y" "arch/${ARCH}/configs/${LINUX_DEFCONFIG}"` ]]; then
	:;
else
	echo "CONFIG_CIFS_POSIX=y" >> arch/${ARCH}/configs/${LINUX_DEFCONFIG};
fi
}
