#!/bin/bash

debian_release (){
DEB_URL="http://deb.debian.org/debian"
if [[ "$DISTRO_VERSION" == "bullseye" ]]; then POOL="main contrib non-free"; else POOL="main contrib non-free non-free-firmware"; fi
if [[ "$DISTRO_VERSION" =~ ^(bullseye|bookworm)$ ]]; then
	tee ${SOURCES_LIST} <<EOF
deb ${DEB_URL} ${DISTRO_VERSION} ${POOL}
deb ${DEB_URL} ${DISTRO_VERSION}-updates ${POOL}
deb ${DEB_URL} ${DISTRO_VERSION}-proposed-updates ${POOL}
deb ${DEB_URL}-security ${DISTRO_VERSION}-security ${POOL}
deb ${DEB_URL} ${DISTRO_VERSION}-backports ${POOL}
EOF
else
	tee ${SOURCES_LIST} <<EOF
deb ${DEB_URL} ${DISTRO_VERSION} ${POOL}
EOF
fi
}

devuan_release (){
DEB_URL="http://deb.devuan.org/merged"
if [[ "$DISTRO_VERSION" == "chimaera" ]]; then POOL="main contrib non-free"; else POOL="main contrib non-free non-free-firmware"; fi
if [[ "$DISTRO_VERSION" =~ ^(chimaera|daedalus)$ ]]; then
	tee ${SOURCES_LIST} <<EOF
deb ${DEB_URL} ${DISTRO_VERSION} ${POOL}
deb ${DEB_URL} ${DISTRO_VERSION}-updates ${POOL}
deb ${DEB_URL} ${DISTRO_VERSION}-proposed-updates ${POOL}
deb ${DEB_URL} ${DISTRO_VERSION}-security ${POOL}
deb ${DEB_URL} ${DISTRO_VERSION}-backports ${POOL}
EOF
else
	tee ${SOURCES_LIST} <<EOF
deb ${DEB_URL} ${DISTRO_VERSION} ${POOL}
EOF
fi
}

raspbian_release (){
DEB_URL="http://raspbian.raspberrypi.org/raspbian"
POOL="main contrib non-free"
tee ${SOURCES_LIST} <<EOF
deb ${DEB_URL} ${DISTRO_VERSION} ${POOL} rpi

# optional
#deb http://archive.raspbian.org/raspbian ${DISTRO_VERSION} ${POOL}
#deb http://mirrordirector.raspbian.org/raspbian ${DISTRO_VERSION} ${POOL}
EOF
}

ubuntu_release (){
DEB_URL="http://ports.ubuntu.com/ubuntu-ports/"
tee ${SOURCES_LIST} <<EOF
deb ${DEB_URL} ${DISTRO_VERSION} main restricted
deb ${DEB_URL} ${DISTRO_VERSION}-updates main restricted
deb ${DEB_URL} ${DISTRO_VERSION} universe
deb ${DEB_URL} ${DISTRO_VERSION}-updates universe
deb ${DEB_URL} ${DISTRO_VERSION} multiverse
deb ${DEB_URL} ${DISTRO_VERSION}-updates multiverse
deb ${DEB_URL} ${DISTRO_VERSION}-backports main restricted universe multiverse
deb ${DEB_URL} ${DISTRO_VERSION}-security main restricted
deb ${DEB_URL} ${DISTRO_VERSION}-security universe
deb ${DEB_URL} ${DISTRO_VERSION}-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu ${DISTRO_VERSION} partner
# deb-src http://archive.canonical.com/ubuntu ${DISTRO_VERSION} partner
EOF
}

choose_release (){
rm -f ${SOURCES_LIST}
if [[ "$DISTRO" =~ ^(debian|devuan|raspbian|ubuntu)$ ]]; then
	${DISTRO}_release
else
	echo "${CAP_DISTRO} ${CAP_RELEASE} is not supported."
	exit 1
fi
}
