#!/bin/bash

mirrors (){
source mirror.txt
if [[ "$DISTRO" == "debian" ]]; then MIRROR="${DEBIAN_MIRROR}"; else
if [[ "$DISTRO" == "devuan" ]]; then MIRROR="${DEVUAN_MIRROR}"; else
if [[ "$DISTRO" == "kali" ]]; then MIRROR="${KALI_MIRROR}"; else
if [[ "$DISTRO" == "raspbian" ]]; then MIRROR="http://raspbian.raspberrypi.org/raspbian"; else
if [[ "$DISTRO" == "ubuntu" ]]; then MIRROR="${UBUNTU_MIRROR}"; fi; fi; fi; fi; fi
}

# DEBIAN
debian_sources_list (){
SOURCES_LIST="${P_VALUE}/etc/apt/sources.list.d/${DISTRO}.sources"
}

debian_release (){
if [[ "$DISTRO_VERSION" == "bullseye" ]]; then POOL="main contrib non-free"; else POOL="main contrib non-free non-free-firmware"; fi
if [[ "$DISTRO_VERSION" =~ ^(bullseye|bookworm|trixie|testing)$ ]]; then
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION} ${DISTRO_VERSION}-updates ${DISTRO_VERSION}-proposed-updates ${DISTRO_VERSION}-backports
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}-security
Suites: ${DISTRO_VERSION}-security
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF
else
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF
fi
}

# DEVUAN
devuan_sources_list (){
SOURCES_LIST="${P_VALUE}/etc/apt/sources.list.d/${DISTRO}.sources"
}

devuan_release (){
if [[ "$DISTRO_VERSION" == "chimaera" ]]; then POOL="main contrib non-free"; else POOL="main contrib non-free non-free-firmware"; fi
if [[ "$DISTRO_VERSION" =~ ^(chimaera|daedalus)$ ]]; then
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION} ${DISTRO_VERSION}-updates ${DISTRO_VERSION}-proposed-updates ${DISTRO_VERSION}-backports
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/devuan-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}-security
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/devuan-archive-keyring.gpg
EOF
else
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/devuan-archive-keyring.gpg
EOF
fi
}

# KALI
kali_sources_list (){
SOURCES_LIST="${P_VALUE}/etc/apt/sources.list.d/${DISTRO}.sources"
}

kali_release (){
# https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
POOL="main contrib non-free non-free-firmware"
tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/kali-archive-keyring.gpg
EOF
}

# RASPBIAN
raspbian_sources_list (){
SOURCES_LIST="${P_VALUE}/etc/apt/sources.list"
}

raspbian_release (){
POOL="main contrib non-free"
tee ${SOURCES_LIST} <<EOF
deb ${MIRROR} ${DISTRO_VERSION} ${POOL} rpi

# optional
#deb http://archive.raspbian.org/raspbian ${DISTRO_VERSION} ${POOL}
#deb http://mirrordirector.raspbian.org/raspbian ${DISTRO_VERSION} ${POOL}
EOF
}

# UBUNTU
ubuntu_sources_list (){
SOURCES_LIST="${P_VALUE}/etc/apt/sources.list.d/${DISTRO}.sources"
}

ubuntu_release (){
tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION} ${DISTRO_VERSION}-updates ${DISTRO_VERSION}-backports
Components: main restricted universe multiverse
Enabled: yes
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}-security
Components: main restricted universe multiverse
Enabled: yes
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF
}

choose_release (){
if [[ "$DISTRO" =~ ^(debian|devuan|kali|raspbian|ubuntu)$ ]]; then
	${DISTRO}_release
else
	echo "${CAP_DISTRO} ${CAP_RELEASE} is not supported."
	exit 0
fi
}
