#!/bin/bash

set -e

# dev rootfs
sysroot_partition (){
for v in IMGSIZE ROOTFS_FOLDER RELEASE_NAME IMAGE_LOOP_DEV ROOT IMAGE_LOOP_DEV_ROOTFS
do
	if [[ -z "$$v" ]]; then
		echo "E: Variable $v empty."
		exit 1
	fi
done
truncate -s ${IMGSIZE} "${ROOTFS_FOLDER}${RELEASE_NAME}"
parted --script "${ROOTFS_FOLDER}${RELEASE_NAME}" \
mklabel msdos \
mkpart primary ext2 1MiB 100%
IMAGE_LOOP_DEV="$(losetup --show -P -f ${ROOTFS_FOLDER}${RELEASE_NAME})"
IMAGE_LOOP_DEV_ROOTFS="${IMAGE_LOOP_DEV}p1"
partprobe "${IMAGE_LOOP_DEV}"
mkfs.ext4 -L ROOTFS "${IMAGE_LOOP_DEV_ROOTFS}"
mkdir -p ${ROOT}
mount "${IMAGE_LOOP_DEV_ROOTFS}" ${ROOT}
sync
umount ${ROOT}
mount -o defaults,noatime "${IMAGE_LOOP_DEV_ROOTFS}" ${ROOT}
}

sysroot_setup (){
for v in VERBOSE ROOT
do
	if [[ -z "$$v" ]]; then
		echo "E: Variable $v empty."
		exit 1
	fi
done
SOURCES_LIST="${ROOT}/etc/apt/sources.list"
mkdir -p ${ROOT}/etc/apt/apt.conf.d ${ROOT}/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "${ROOT}/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"
if [ $VERBOSE -eq 1 ]; then
	choose_release
else
	choose_release > /dev/null 2>&1
fi
}

devuan_keyring (){
URL="https://pkgmaster.devuan.org/devuan/pool/main/d/devuan-keyring/"
FILE="devuan-keyring_2023.10.07_all.deb"
if [[ `dpkg -l | grep "devuan-keyring"` ]]; then
	if [[ `dpkg -l | grep "devuan-keyring" | tr -d -c 0-9` == "20231007" ]]; then
		:;
	else
		apt purge -y devuan-keyring
		wget -cq --show-progress ${URL}${FILE}; dpkg -i ${FILE}; rm -f ${FILE}
	fi
else
	wget -cq --show-progress ${URL}${FILE}; dpkg -i ${FILE}; rm -f ${FILE}
fi
}

raspbian_keyring (){
if [[ -f "/usr/share/keyrings/raspbian-archive-keyring.gpg" ]]; then
	:;
else
	curl -sS http://archive.raspbian.org/raspbian.public.key | gpg --dearmor | tee /usr/share/keyrings/raspbian-archive-keyring.gpg > /dev/null 2>&1
fi
}

ubuntu_setup (){
if [[ "$HOST_ARCH" == "x86_64" ]]; then
	MACHINE="amd64"
fi
if [[ "$HOST_ARCH" == "aarch64" ]]; then
	MACHINE="arm64"
fi
URL="https://github.com/pyavitz/debian-image-builder/releases/download/dpkg/"
FILE1="dpkg_1.21.2_$MACHINE.deb"
FILE2="debootstrap_1.0.126+nmu1_all.deb"
FILE3="ubuntu-keyring_2020.06.17.1-1_all.deb"
FILE4="ubuntu-archive-keyring_2020.06.17.1-1_all.deb"
FILE5="ubuntu-cloud-keyring_2020.06.17.1-1_all.deb"
FILE6="ubuntu-dbgsym-keyring_2020.06.17.1-1_all.deb"
if [[ `grep -w "Ubuntu" "/etc/os-release"` ]] && [[ `grep -w "VERSION_CODENAME=jammy" "/etc/os-release"` ]]; then
	:;
else
	if [[ `apt show dpkg | grep "Version: 1.21"` ]] > /dev/null 2>&1; then
		:;
	else
		wget -cq $URL$FILE1
		wget -cq $URL$FILE2
		dpkg -i *.deb
		rm -f *.deb
	fi
fi
if [ -e /usr/share/keyrings/ubuntu-archive-keyring.gpg ]; then
	:;
else
	wget -cq --show-progress $URL$FILE3
	wget -cq --show-progress $URL$FILE4
	wget -cq --show-progress $URL$FILE5
	wget -cq --show-progress $URL$FILE6
	dpkg -i *.deb
	rm -f *.deb
fi
}

debootstrap_script (){
if [[ -f "/usr/share/debootstrap/scripts/${DISTRO_VERSION}" ]]; then
	:;
else
	ln -sr /usr/share/debootstrap/scripts/${DEBOOTSTRAP_SCRIPT} /usr/share/debootstrap/scripts/${DISTRO_VERSION}
	sleep .50
fi
}

# debootstrap
run_debootstrap (){
if [[ -z "$ROOT" ]]; then
	echo "E (run_debootstrap): Variable ROOT not set."
	exit 1
fi
KEY_DIR="/usr/share/keyrings"
if [[ "$DISTRO" == "devuan" ]]; then
	DEBOOTSTRAP_SCRIPT="sid"
	debootstrap_script
elif [[ "$DISTRO" == "ubuntu" ]]; then
	DEBOOTSTRAP_SCRIPT="gutsy"
	debootstrap_script
elif [[ "$DISTRO" == "debian" || "$DISTRO" == "kali" || "$DISTRO" == "ubuntu" ]]; then
	debootstrap --arch ${ARCH_EXT} --foreign ${DISTRO_VERSION} ${ROOT}
	chroot ${ROOT} /debootstrap/debootstrap --second-stage
elif [[ "$DISTRO" == "devuan" ]]; then
	KEY="${KEY_DIR}/devuan-archive-keyring.gpg"
	SOURCE="http://deb.devuan.org/merged"
	debootstrap --arch ${ARCH_EXT} --foreign --force-check-gpg --keyring=$KEY ${DISTRO_VERSION} ${ROOT} ${SOURCE}
	chroot ${ROOT} /debootstrap/debootstrap --second-stage
elif [[ "$DISTRO" == "raspbian" ]]; then
	KEY="${KEY_DIR}/raspbian-archive-keyring.gpg"
	SOURCE="http://raspbian.raspberrypi.org/raspbian"
	debootstrap --arch ${ARCH_EXT} --foreign --force-check-gpg --keyring=$KEY ${DISTRO_VERSION} ${ROOT} ${SOURCE}
	chroot ${ROOT} /debootstrap/debootstrap --second-stage
else
	echo "E (run_debootstrap): Variable DISTRO not set."
	exit 1
fi
}
