#!/bin/bash
GIT_URL="https://github.com/raspberrypi/linux"
ITL="\033[3m"

source_dir (){
mkdir -p ${SRC}
cp -f board.txt ${SRC}/
cd ${SRC}
}

noinitrd (){ # no longer used
sed -i 's/export INITRD=$want_initrd/export INITRD=No/g' scripts/package/builddeb
sed -i 's/export INITRD=$(if_enabled_echo CONFIG_BLK_DEV_INITRD Yes No)/export INITRD=No/g' scripts/package/builddeb
}

download (){
if [[ `wget -S --spider ${GIT_URL}/blob/rpi-${VERSION}/Makefile 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	download_options
	if [[ "$GIT_SHALLOW" == "true" ]]; then verify_commit; fi
	if [[ -d "${KERNEL}-${VERSION}" ]] && [[ -d "${KERNEL}-${VERSION}.backup" ]]; then
		echo -en "${KERNEL}" | sed -e "s/\b\(.\)/\u\1/g"; echo -en "-${VERSION}:"
		echo -en " Restoring"
		rm -fdr ${KERNEL}-${VERSION}
		mv -f ${KERNEL}-${VERSION}.backup ${KERNEL}-${VERSION}
		if [[ "$GIT_SHALLOW" == "false" ]]; then
			cd ${KERNEL}-${VERSION}; git pull -q; make clean; cd ..
		else
			cd ${KERNEL}-${VERSION}; make clean; cd ..
		fi
		cp -r ${KERNEL}-${VERSION} ${KERNEL}-${VERSION}.backup
		echo -e ", done."
	else
		echo -e "This may take a while ..."
		echo ""
		git clone ${GIT_OPT} -b rpi-${VERSION} ${GIT_URL}.git ${KERNEL}-${VERSION}
		sleep .50
		if [[ -d "${KERNEL}-${VERSION}" ]] && [[ -f "${KERNEL}-${VERSION}/Makefile" ]]; then
			cd ${KERNEL}-${VERSION}; make clean; cd ..
			echo -en "${KERNEL}" | sed -e "s/\b\(.\)/\u\1/g"; echo -en "-${VERSION}:"
			echo -en " Creating backup"
			cp -r ${KERNEL}-${VERSION} ${KERNEL}-${VERSION}.backup
			echo -e ", done."
		else
			echo -en "${KERNEL}" | sed -e "s/\b\(.\)/\u\1/g"; echo -en "-${VERSION}:"
			echo -en " Download"
			echo -e ", failed."
			exit 0
		fi
	fi
else
	echo ""
	echo -e "Git branch ${VERSION} is not available?"
	exit 0
fi
}

download_options (){
GIT_HASH=`git ls-remote --heads ${GIT_URL}.git | grep -w "refs/heads/rpi-${VERSION}" | sed -n '1p' | sed "s/refs\/heads\/rpi-${VERSION}//g" | sed s/'\s'//g`
if [[ -f "../.cache/git_shallow.${KERNEL}-${VERSION}" ]] && [[ -d "${KERNEL}-${VERSION}" ]]; then
	:;
else
	rm -f ../.cache/git_shallow.${KERNEL}-${VERSION}
	rm -fdr ${KERNEL}-${VERSION}
fi
if [[ -f "../.cache/git_shallow.${KERNEL}-${VERSION}" ]]; then
	source ../.cache/git_shallow.${KERNEL}-${VERSION}
	if [[ "$GIT_SHALLOW" == "true" ]]; then GIT_OPT="--depth 1"; else GIT_OPT=""; fi
else
	mkdir -p ../.cache
	echo 'GIT_SHALLOW="true"' > ../.cache/git_shallow.${KERNEL}-${VERSION}
	echo GIT_COMMIT='"'${GIT_HASH}'"' >> ../.cache/git_shallow.${KERNEL}-${VERSION}
	GIT_OPT="--depth 1"
	echo -e ""
fi
GIT_HASH_SHORT=`echo "${GIT_HASH}" | sed 's/^\(.\{7\}\).*/\1/'`
GIT_COMMIT_SHORT=`echo "${GIT_COMMIT}" | sed 's/^\(.\{7\}\).*/\1/'`
}

verify_commit (){
echo ""
echo -en "Commit:"
if [[ "$GIT_COMMIT" == "$GIT_HASH" ]]; then
	echo -en " ${GIT_COMMIT_SHORT}"
	sleep .50
	echo -e ", ok."
else
	
	echo -en " ${GIT_HASH_SHORT}"
	sleep .50
	echo -e " ${ITL}NEW!${FIN}"
	sed -i 's/^GIT_COMMIT=.*/GIT_COMMIT="'"${GIT_HASH}"'"/' ../.cache/git_shallow.${KERNEL}-${VERSION}
	echo -en "Removing: ${GIT_COMMIT_SHORT}"
	rm -fdr ${KERNEL}-${VERSION} ${KERNEL}-${VERSION}.backup
	echo -e ", done."
	echo ""
fi
}

setup (){
if [[ -d "${KERNEL}-${VERSION}" ]]; then
	cd ${KERNEL}-${VERSION}
	export ARCH=${ARCH}
	if [[ "ARCH" == "arm" ]]; then KERNEL=${KERNEL_VAR}; fi
else
	report_dir_error
fi
}

cconfig (){
echo_cconfig
if [[ -f "../../defconfig/${MYCONFIG}" ]]; then
	cp -f ../../defconfig/${MYCONFIG} arch/${ARCH}/configs/
else
	echo ""
	echo -e "${MYCONFIG} was not found."
	echo -e "Check that the name is correct and in the correct location."
	echo -e "If you believe you are receiving this in error, please report it."
	read -p "Press enter to continue."
	exit 1
fi
kbuild "${MYCONFIG}"
echo ""
}

fconfig (){
echo -e "${WHT}Making ${LINUX_DEFCONFIG}${FIN}."
linux_configs
kbuild "${LINUX_DEFCONFIG}"
echo ""
}

save_defconfig (){
if [[ -f "defconfig" ]]; then
	echo ""
	mkdir -p ../../$OUTPUT/
	# minimal
	cp -f defconfig ../../$OUTPUT/${BOARD}_defconfig
	# full
	cp -f .config ../../$OUTPUT/${BOARD}-config_defconfig
	# path to files
	ls -ls ../../$OUTPUT/${BOARD}_defconfig | sed 's/..\/..\///g'
	ls -ls ../../$OUTPUT/${BOARD}-config_defconfig | sed 's/..\/..\///g'
fi
}

menuconfig (){
echo ""
echo_menuconfig
sleep .50
kbuild "menuconfig"
sleep .25
kbuild "savedefconfig"
echo "# ${BOARD} defconfig saved."
options=("Continue" "Quit")
select opt in "${options[@]}"
do
	case $opt in
		"Continue")
			save_defconfig
			break
			;;
		"Quit")
			save_defconfig
			exit 0
			;;
		*) echo "invalid option $REPLY";;
	esac
done
}

builddeb (){
if [ $CROSSCOMPILE -eq 1 ]; then echo -e "${GRN}  CC${FIN}      ${CROSS_COMPILE}${COMPILER}"; else echo -e "${GRN}  NC${FIN}      ${COMPILER}"; fi
echo ${BUILD_VERSION} > .version
echo 'y' | kbuild "LOCALVERSION= KBUILD_BUILD_USER=${KBUSER} KBUILD_BUILD_HOST=${KBHOST} bindeb-pkg"
}
