#!/bin/bash

# STAGE 1
distro_release(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION} main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-updates main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION} universe
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-updates universe
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION} multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-updates multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-backports main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-security main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-security universe
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu ${DISTRO_VERSION} partner
# deb-src http://archive.canonical.com/ubuntu ${DISTRO_VERSION} partner
EOF
}

# STAGE 2
apt_preferences(){
echo
echo Blacking listing packages.
tee /etc/apt/preferences <<EOF
Package: rpi-eeprom linux-firmware linux-firmware-raspi2 pi-bluetooth raspberrypi-sys-mods
Pin: release o=Ubuntu
Pin-Priority: 1
EOF
echo Done.
}
