#!/bin/bash

# RTL8812AU
rtl8812au_download(){
if [ -e rtl8812au ]; then
	echo -en "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN} ";
	cd rtl8812au;
	git config pull.rebase false;
	echo -en "${PNK}[${FIN}${WHT}pulling${FIN}${PNK}]${FIN} ";
	git pull -q;
	cd ..;
else
	echo -en "${PNK}[${FIN}${WHT}cloning${FIN}${PNK}]${FIN} ";
	git clone -q https://github.com/pyavitz/rtl8812au.git rtl8812au;
fi
}

rtl8812au(){
rm -fdr drivers/net/wireless/rtl8812au
mkdir -p drivers/net/wireless/rtl8812au
cp -R ../rtl8812au/{core,hal,include,os_dep,platform} drivers/net/wireless/rtl8812au
cp -R ../rtl8812au/Makefile drivers/net/wireless/rtl8812au/Makefile
cp -R ../rtl8812au/Kconfig drivers/net/wireless/rtl8812au/Kconfig
echo "obj-\$(CONFIG_88XXAU) += rtl8812au/" >> "drivers/net/wireless/Makefile"
sed -i '/source "drivers\/net\/wireless\/ti\/Kconfig"/a source "drivers\/net\/wireless\/rtl8812au\/Kconfig"' drivers/net/wireless/Kconfig
}

rtl8812au_select(){
if [ -e arch/${ARCH}/configs/${LINUX_DEFCONFIG} ]; then
	echo CONFIG_88XXAU=m >> arch/${ARCH}/configs/${LINUX_DEFCONFIG};
fi
}

rtl8812au_module(){
if [ $rtl8812au -eq 1 ]; then
	rtl8812au_select;
fi
}

# RTL8811CU
rtl8811cu_download(){
if [ -e rtl8811cu ]; then
	echo -en "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN} ";
	cd rtl8811cu;
	git config pull.rebase false;
	echo -en "${PNK}[${FIN}${WHT}pulling${FIN}${PNK}]${FIN} ";
	git pull -q;
	cd ..;
else
	echo -en "${PNK}[${FIN}${WHT}cloning${FIN}${PNK}]${FIN} ";
	git clone -q https://github.com/morrownr/8821cu-20210118.git rtl8811cu;
fi
}

rtl8811cu(){
rm -fdr drivers/net/wireless/rtl8811cu
mkdir -p drivers/net/wireless/rtl8811cu
cp -R ../rtl8811cu/{core,hal,include,os_dep,platform,rtl8821c.mk,halmac.mk} drivers/net/wireless/rtl8811cu
cp -R ../rtl8811cu/Makefile drivers/net/wireless/rtl8811cu/Makefile
cp -R ../rtl8811cu/Kconfig drivers/net/wireless/rtl8811cu/Kconfig
sed -i 's/---help---/help/g' drivers/net/wireless/rtl8811cu/Kconfig
sed -i "s/^CONFIG_RTW_DEBUG.*/CONFIG_RTW_DEBUG = n/" drivers/net/wireless/rtl8811cu/Makefile
sed -i "s/^CONFIG_MP_VHT_HW_TX_MODE.*/CONFIG_MP_VHT_HW_TX_MODE = n/" drivers/net/wireless/rtl8811cu/Makefile
echo "obj-\$(CONFIG_RTL8821CU) += rtl8811cu/" >> drivers/net/wireless/Makefile
sed -i '/source "drivers\/net\/wireless\/ti\/Kconfig"/a source "drivers\/net\/wireless\/rtl8811cu\/Kconfig"' drivers/net/wireless/Kconfig
}

rtl8811cu_select(){
if [ -e arch/${ARCH}/configs/${LINUX_DEFCONFIG} ]; then
	echo CONFIG_RTL8821CU=m >> arch/${ARCH}/configs/${LINUX_DEFCONFIG};
fi
}

rtl8811cu_module(){
if [ $rtl8811cu -eq 1 ]; then
	rtl8811cu_select;
fi
}


# RTL88X2BU
rtl88x2bu_download(){
if [ -e rtl88x2bu ]; then
	echo -en "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN} ";
	cd rtl88x2bu;
	git config pull.rebase false;
	echo -en "${PNK}[${FIN}${WHT}pulling${FIN}${PNK}]${FIN} ";
	git pull -q;
	cd ..;
else
	echo -en "${PNK}[${FIN}${WHT}cloning${FIN}${PNK}]${FIN} ";
	git clone -q https://github.com/RinCat/RTL88x2BU-Linux-Driver.git rtl88x2bu;
fi
}

rtl88x2bu(){
rm -fdr drivers/net/wireless/rtl88x2bu
mkdir -p drivers/net/wireless/rtl88x2bu
cp -R ../rtl88x2bu/{core,hal,include,os_dep,platform,halmac.mk,rtl8822b.mk} drivers/net/wireless/rtl88x2bu
cp -f ../rtl88x2bu/Makefile drivers/net/wireless/rtl88x2bu/Makefile
cp -f ../rtl88x2bu/Kconfig drivers/net/wireless/rtl88x2bu/Kconfig
sed -i 's/---help---/help/g' drivers/net/wireless/rtl88x2bu/Kconfig
sed -i 's/include $(src)\/rtl8822b.mk /include $(TopDIR)\/drivers\/net\/wireless\/rtl88x2bu\/rtl8822b.mk/' \
drivers/net/wireless/rtl88x2bu/Makefile
echo "obj-\$(CONFIG_RTL8822BU) += rtl88x2bu/" >> drivers/net/wireless/Makefile
sed -i '/source "drivers\/net\/wireless\/ti\/Kconfig"/a source "drivers\/net\/wireless\/rtl88x2bu\/Kconfig"' \
drivers/net/wireless/Kconfig
}

rtl88x2bu_select(){
if [ -e arch/${ARCH}/configs/${LINUX_DEFCONFIG} ]; then
	echo CONFIG_RTL8822BU=m >> arch/${ARCH}/configs/${LINUX_DEFCONFIG};
fi
}

rtl88x2bu_module(){
if [ $rtl88x2bu -eq 1 ]; then
	rtl88x2bu_select;
fi
}

extra_wireless(){
echo ""
if [ $rtl8812au -eq 1 ]; then
	echo -en "${WHT}Realtek 88XXAU${FIN} ";
	rtl8812au_download;
	echo_bdone;
fi
if [ $rtl88x2bu -eq 1 ]; then
	echo -en "${WHT}Realtek 88X2BU${FIN} ";
	rtl88x2bu_download;
	echo_bdone;
fi
if [ $rtl8811cu -eq 1 ]; then
	echo -en "${WHT}Realtek 88XXCU${FIN} ";
	rtl8811cu_download;
	echo_bdone;
fi
}
