#!/bin/bash

driver_download (){
if [[ -d "${DRIVER}" ]]; then
	echo -en "${DRIVER_INFO}:"
	cd ${DRIVER}
	git config pull.rebase false
	echo -en " Pulling"
	git pull -q
	cd ..
	echo -e ", done."
else
	echo -en "${DRIVER_INFO}:"
	echo -en " Cloning"
	git clone -q ${DRIVER_URL} ${DRIVER}
	echo -e ", done."
fi
}

# RTW88
extra_wireless (){
if [ $RTW88 -eq 1 ]; then
	DRIVER_INFO="Realtek WiFi 5"
	DRIVER="rtw88"
	DRIVER_URL="https://github.com/lwfinger/${DRIVER}.git"
	driver_download
	rm -fdr ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	mkdir -p ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	cp -fr ${DRIVER}/* ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/
	rm -fdr ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/{alt_rtl8821ce,README.md}
fi
}
