#!/bin/bash
source /etc/opt/board.txt

create_user(){
adduser ${USERNAME} --gecos ${NAME} --disabled-password
echo "${USERNAME}:${PASSWORD}" | chpasswd
adduser ${USERNAME} sudo
adduser ${USERNAME} audio
adduser ${USERNAME} dialout
adduser ${USERNAME} video
adduser ${USERNAME} disk
adduser ${USERNAME} plugdev
adduser ${USERNAME} netdev
adduser ${USERNAME} bluetooth
adduser ${USERNAME} input
adduser ${USERNAME} tty
adduser ${USERNAME} i2c
if [[ `grep -w "gpio" "/etc/group"` ]]; then
	adduser ${USERNAME} gpio;
else
	groupadd gpio;
	adduser ${USERNAME} gpio;
fi
if [[ `grep -w "spi" "/etc/group"` ]]; then
	adduser ${USERNAME} spi;
else
	groupadd spi;
	adduser ${USERNAME} spi;
fi
}

create_sudoers(){
if [ -f /etc/sudoers.d/010_pi-nopasswd ]; then
	rm -f /etc/sudoers.d/010_pi-nopasswd;
fi
tee /etc/sudoers.d/010_${USERNAME}-nopasswd <<EOF
${USERNAME} ALL=(ALL) NOPASSWD: ALL
EOF
}

account_prompt(){
echo -en "${FAMILY}: " | sed -e 's/\(.*\)/\U\1/'
echo -e "${BOARD}" | sed -e 's/\(.*\)/\U\1/'
echo ""
echo -e "\e[1;37mWelcome. Create a User Account\e[0m."
echo ""
echo -en "Name: "
read NAME
echo -en "Username: "
read USERNAME
while true; do
	echo -en "Password: "
	read FIRST
	echo -en "Password (again): "
	read SECOND
	if [ "$FIRST" = "$SECOND" ]; then
		PASSWORD="${FIRST}";
		echo "";
		echo -e "Creating a user account for: \e[1;37m${NAME}\e[0m ...";
	else
		echo -e "The passwords don't match. Try again.";
		continue;
	fi
	break
done
}

if [ -f /boot/useraccount.txt ]; then
	# headless
	source /boot/useraccount.txt;
	echo -en "${FAMILY}: " | sed -e 's/\(.*\)/\U\1/'
	echo -e "${BOARD}" | sed -e 's/\(.*\)/\U\1/'
	echo ""
	echo -e "Creating a user account for: \e[1;37m${NAME}\e[0m"
	create_user > /dev/null 2>&1;
	create_sudoers > /dev/null 2>&1;
	rm -f /boot/useraccount.txt
	sleep 1s
else
	# headful
	account_prompt;
	create_user > /dev/null 2>&1;
	create_sudoers > /dev/null 2>&1;
	rm -f /boot/rename_to_useraccount.txt
	echo "Almost done ...";
	sleep 1s;
fi
if [[ `grep -w "Debian" "/etc/os-release"` ]]; then
	systemctl disable useraccount > /dev/null 2>&1;
else
	if [[ `grep -w "Devuan" "/etc/os-release"` ]]; then
		update-rc.d useraccount remove > /dev/null 2>&1;
	else
		if [[ `grep -w "Ubuntu" "/etc/os-release"` ]]; then
			systemctl disable useraccount > /dev/null 2>&1;
		fi
	fi
fi
sleep 1s
if [ -e /home/${USERNAME} ]; then
	sleep 1s
	mkdir -p /home/${USERNAME}/.config/mc/;
	mv -f /etc/opt/user-ini /home/${USERNAME}/.config/mc/ini;
	mv -f /etc/opt/nanorc-user /home/${USERNAME}/.nanorc;
	chown -R ${USERNAME}:${USERNAME} /home/${USERNAME};
	rm -f /etc/opt/{nanorc-user,user-ini};
fi
if [[ `grep -w "Devuan" "/etc/os-release"` ]]; then
	clear -x;
fi

exit 0
