#!/bin/bash

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
fi
if [[ -f "/boot/broadcom/useraccount.txt" ]]; then
	. /boot/broadcom/useraccount.txt
fi
RELEASE=`cat /etc/os-release | grep -w NAME | sed 's/NAME=//g' | sed 's/"//g' | sed 's/ GNU\/Linux//g'`

create_user(){
adduser ${USERNAME} --gecos ${NAME} --disabled-password
echo "${USERNAME}:${PASSWORD}" | chpasswd
adduser ${USERNAME} sudo
adduser ${USERNAME} audio
adduser ${USERNAME} dialout
adduser ${USERNAME} video
adduser ${USERNAME} disk
adduser ${USERNAME} plugdev
adduser ${USERNAME} netdev
adduser ${USERNAME} bluetooth
adduser ${USERNAME} input
adduser ${USERNAME} render
adduser ${USERNAME} tty
adduser ${USERNAME} i2c
if [[ `grep -w "gpio" "/etc/group"` ]]; then
	adduser ${USERNAME} gpio
else
	groupadd gpio;
	adduser ${USERNAME} gpio
fi
if [[ `grep -w "spi" "/etc/group"` ]]; then
	adduser ${USERNAME} spi
else
	groupadd spi;
	adduser ${USERNAME} spi
fi
}

create_sudoers(){
if [[ -f "/etc/sudoers.d/010_pi-nopasswd" ]]; then
	rm -f /etc/sudoers.d/010_pi-nopasswd
fi
tee /etc/sudoers.d/010_${USERNAME}-nopasswd <<EOF
${USERNAME} ALL=(ALL) NOPASSWD: ALL
EOF
}

account_prompt(){
echo -en "${FAMILY}: " | sed -e 's/\(.*\)/\U\1/'
echo -e "${BOARD}" | sed -e 's/\(.*\)/\U\1/'
echo ""
echo -e "\e[1;37mWelcome. Create a User Account\e[0m."
echo ""
echo -en "Name: "
read NAME
echo -en "Username: "
read USERNAME
while true; do
	echo -en "Password: "
	read FIRST
	echo -en "Password (again): "
	read SECOND
	if [ "$FIRST" = "$SECOND" ]; then
		PASSWORD="${FIRST}"
		echo "";
		echo -e "Creating a user account for: \e[1;37m${NAME}\e[0m ..."
	else
		echo -e "The passwords don't match. Try again."
		continue
	fi
	break
done
}

if [[ "$ENABLE" == "true" || "$ENABLE" == "yes" || "$ENABLE" == "enable" ]]; then
	# headless
	echo -en "${FAMILY}: " | sed -e 's/\(.*\)/\U\1/'
	echo -e "${BOARD}" | sed -e 's/\(.*\)/\U\1/'
	echo ""
	echo -e "Creating a user account for: \e[1;37m${NAME}\e[0m"
	create_user > /dev/null 2>&1
	create_sudoers > /dev/null 2>&1
	rm -f /boot/broadcom/useraccount.txt
	echo "Almost done ..."
	sleep 1s
else
	# headful
	account_prompt
	create_user > /dev/null 2>&1
	create_sudoers > /dev/null 2>&1
	rm -f /boot/broadcom/useraccount.txt
	echo "Almost done ..."
	sleep 1s
fi
if [[ "$RELEASE" == "Debian" || "$RELEASE" == "Ubuntu" ]]; then
	systemctl disable useraccount > /dev/null 2>&1
fi
if [[ "$RELEASE" == "Devuan" ]]; then
	update-rc.d useraccount remove > /dev/null 2>&1
fi
sleep 1s
if [ -e /home/${USERNAME} ]; then
	sleep 1s
	mkdir -p /home/${USERNAME}/.config/mc/
	mv -f /etc/opt/user-ini /home/${USERNAME}/.config/mc/ini
	mv -f /etc/opt/nanorc-user /home/${USERNAME}/.nanorc
	chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
	rm -f /etc/opt/{nanorc-user,user-ini}
fi
if [[ "$RELEASE" == "Devuan" ]]; then
	clear -x
fi

exit 0
