#!/bin/bash
source /boot/credentials.txt

### Functions
dhcp () {
sed -i "s/REGDOMAIN=/REGDOMAIN=${COUNTRYCODE}/g" /etc/default/crda
iw reg set ${COUNTRYCODE}
nmcli c add type wifi con-name ${NAME} ifname wlan0 ssid ${SSID}
nmcli c modify ${NAME} wifi-sec.key-mgmt wpa-psk wifi-sec.psk ${PASSKEY}
nmcli c up ${NAME}
}

static () {
sed -i "s/REGDOMAIN=/REGDOMAIN=${COUNTRYCODE}/g" /etc/default/crda
iw reg set ${COUNTRYCODE}
nmcli c add type wifi con-name ${NAME} ifname wlan0 ssid ${SSID}
nmcli c modify ${NAME} wifi-sec.key-mgmt wpa-psk wifi-sec.psk ${PASSKEY}
nmcli con mod ${NAME} ipv4.addresses ${IPADDR}/24
nmcli con mod ${NAME} ipv4.gateway ${GATEWAY}
nmcli con mod ${NAME} ipv4.method manual
nmcli con mod ${NAME} ipv4.dns "${DNS}"
nmcli c up ${NAME}
}

connect_wifi () {
case `grep -Fx "MANUAL=y" "/boot/credentials.txt" >/dev/null; echo $?` in
  0)
    static
    ;;
  1)
    dhcp
    ;;
esac
}

remove_wifi () {
systemctl disable credentials
rm -f /usr/local/bin/credentials > /dev/null 2>&1
rm -f /boot/rename_to_credentials.txt > /dev/null 2>&1
}

### Check Credentials
if ls /boot/username.txt > /dev/null 2>&1; then /usr/local/bin/whogoesthere > /dev/null 2>&1;
        else : > /dev/null 2>&1;
fi
if touch -c /boot/credentials.txt 2>/dev/null; then connect_wifi;
        else remove_wifi > /dev/null 2>&1;
fi

### Clean
systemctl disable credentials
rm -f /usr/local/bin/credentials > /dev/null 2>&1
rm -f /boot/credentials.txt > /dev/null 2>&1
