#!/bin/bash
source /boot/credentials.txt

### Functions
change_hostname(){
sed -i "s/bcm2711/${HOSTNAME}/g" /etc/hostname
sed -i "s/bcm2710/${HOSTNAME}/g" /etc/hostname
sed -i "s/bcm2708/${HOSTNAME}/g" /etc/hostname
sed -i "s/musicbox/${HOSTNAME}/g" /etc/hostname
sed -i "s/bcm2711/${HOSTNAME}/g" /etc/hosts
sed -i "s/bcm2710/${HOSTNAME}/g" /etc/hosts
sed -i "s/bcm2708/${HOSTNAME}/g" /etc/hosts
sed -i "s/musicbox/${HOSTNAME}/g" /etc/hosts
}

change_branding(){
sed -i "s/Raspberry Pi/${BRANDING}/g" /etc/update-motd.d/15-brand
sed -i "s/Raspberry Pi/${BRANDING}/g" /etc/update-motd.d/15-brand
sed -i "s/Raspberry Pi/${BRANDING}/g" /etc/update-motd.d/15-brand
sed -i "s/Musicbox/${BRANDING}/g" /etc/update-motd.d/15-brand
}

dhcp () {
sed -i "s/REGDOMAIN=/REGDOMAIN=${COUNTRYCODE}/g" /etc/default/crda
iw reg set ${COUNTRYCODE}
nmcli c add type wifi con-name ${NAME} ifname wlan0 ssid ${SSID}
nmcli c modify ${NAME} wifi-sec.key-mgmt wpa-psk wifi-sec.psk ${PASSKEY}
nmcli c up ${NAME}
}

static () {
sed -i "s/REGDOMAIN=/REGDOMAIN=${COUNTRYCODE}/g" /etc/default/crda
iw reg set ${COUNTRYCODE}
nmcli c add type wifi con-name ${NAME} ifname wlan0 ssid ${SSID}
nmcli c modify ${NAME} wifi-sec.key-mgmt wpa-psk wifi-sec.psk ${PASSKEY}
nmcli con mod ${NAME} ipv4.addresses ${IPADDR}/24
nmcli con mod ${NAME} ipv4.gateway ${GATEWAY}
nmcli con mod ${NAME} ipv4.method manual
nmcli con mod ${NAME} ipv4.dns "${DNS}"
nmcli c up ${NAME}
}

connect_wifi () {
case `grep -Fx "MANUAL=y" "/boot/credentials.txt" >/dev/null; echo $?` in
  0)
    static
    ;;
  1)
    dhcp
    ;;
esac
}

hostname_branding(){
case `grep -Fx "CHANGE=y" "/boot/credentials.txt" >/dev/null; echo $?` in
  0)
    change_hostname
    change_branding
    hostnamectl set-hostname ${HOSTNAME}
    systemctl restart avahi-daemon
    ;;
esac
}

remove_wifi () {
systemctl disable credentials
rm -f /usr/local/bin/credentials > /dev/null 2>&1
rm -f /boot/rename_to_credentials.txt > /dev/null 2>&1
}

### Renew SSH keys
sleep 1s
/bin/rm -v /etc/ssh/ssh_host_* > /dev/null 2>&1
dpkg-reconfigure openssh-server > /dev/null 2>&1
systemctl restart ssh > /dev/null 2>&1

### Check Credentials
if ls /boot/username.txt > /dev/null 2>&1; then /usr/local/bin/whogoesthere > /dev/null 2>&1;
        else : > /dev/null 2>&1;
fi
if ls /boot/credentials.txt > /dev/null 2>&1; then hostname_branding;
        else : > /dev/null 2>&1;
fi
if touch -c /boot/credentials.txt 2>/dev/null; then connect_wifi;
        else remove_wifi > /dev/null 2>&1;
fi

### Clean
systemctl disable credentials
rm -f /usr/local/bin/credentials > /dev/null 2>&1
rm -f /boot/credentials.txt > /dev/null 2>&1
