#!/bin/bash
### Functions
grow_mmcblk () {
bash growpart /dev/mmcblk0 2 > /dev/null 2>&1
sleep 1s
resize2fs /dev/mmcblk0p2 > /dev/null 2>&1
}

grow_mmcblk1 () {
bash growpart /dev/mmcblk1 2 > /dev/null 2>&1
sleep 1s
resize2fs /dev/mmcblk1p2 > /dev/null 2>&1
}

grow_sda () {
bash growpart /dev/sda 2 > /dev/null 2>&1
sleep 1s
resize2fs /dev/sda2 > /dev/null 2>&1
}

chk_mmcblk () {
fsck.fat -trawl /dev/mmcblk0p1 > /dev/null 2>&1
}

chk_mmcblk1 () {
fsck.fat -trawl /dev/mmcblk1p1 > /dev/null 2>&1
}

chk_sda () {
fsck.fat -trawl /dev/sda1 > /dev/null 2>&1
}

### Grow Partition
if touch -c /dev/mmcblk0 2>/dev/null; then grow_mmcblk;
        else echo "" &>/dev/null;
fi

if touch -c /dev/mmcblk1 2>/dev/null; then grow_mmcblk1;
        else echo "" &>/dev/null;
fi

if touch -c /dev/sda 2>/dev/null; then grow_sda;
        else echo "" &>/dev/null;
fi

### Renew SSH keys
sleep 1s
/bin/rm -v /etc/ssh/ssh_host_* > /dev/null 2>&1
dpkg-reconfigure openssh-server > /dev/null 2>&1
systemctl restart ssh > /dev/null 2>&1

### Fsck boot partition
umount /boot
sleep 1s
if touch -c /dev/mmcblk0 2>/dev/null; then chk_mmcblk;
        else echo "" &>/dev/null;
fi

if touch -c /dev/mmcblk1 2>/dev/null; then chk_mmcblk1;
        else echo "" &>/dev/null;
fi

if touch -c /dev/sda 2>/dev/null; then chk_sda;
        else echo "" &>/dev/null;
fi
sleep 1s
mount /boot

### Clean up
systemctl disable firstboot > /dev/null 2>&1
update-rc.d firstboot remove > /dev/null 2>&1
rm -f /var/cache/debconf/*
rm -f /boot/rename_to_credentials.txt > /dev/null 2>&1
rm -f /usr/local/sbin/firstboot
