#!/bin/bash
### Functions
grow_mmcblk(){
bash growpart /dev/mmcblk0 2 > /dev/null 2>&1
sleep 1s
if blkid | grep ext4 > /dev/null 2>&1;
	then resize2fs /dev/mmcblk0p2 > /dev/null 2>&1
fi
if blkid | grep btrfs > /dev/null 2>&1;
	then btrfs filesystem resize max / > /dev/null 2>&1
fi
if blkid | grep xfs > /dev/null 2>&1;
	then xfs_growfs -d / > /dev/null 2>&1
fi
}

grow_mmcblk1(){
bash growpart /dev/mmcblk1 2 > /dev/null 2>&1
sleep 1s
if blkid | grep ext4 > /dev/null 2>&1;
	then resize2fs /dev/mmcblk1p2 > /dev/null 2>&1
fi
if blkid | grep btrfs > /dev/null 2>&1;
	then btrfs filesystem resize max / > /dev/null 2>&1
fi
if blkid | grep xfs > /dev/null 2>&1;
	then xfs_growfs -d / > /dev/null 2>&1
fi
}

grow_sda(){
bash growpart /dev/sda 2 > /dev/null 2>&1
sleep 1s
if blkid | grep ext4 > /dev/null 2>&1;
	then resize2fs /dev/sda2 > /dev/null 2>&1
fi
if blkid | grep btrfs > /dev/null 2>&1;
	then btrfs filesystem resize max / > /dev/null 2>&1
fi
if blkid | grep xfs > /dev/null 2>&1;
	then xfs_growfs -d / > /dev/null 2>&1
fi
}

grow_nvme(){
bash growpart /dev/nvme0n1 2 > /dev/null 2>&1
sleep 1s
if blkid | grep ext4 > /dev/null 2>&1;
	then resize2fs /dev/nvme0n1p2 > /dev/null 2>&1
fi
if blkid | grep btrfs > /dev/null 2>&1;
	then btrfs filesystem resize max / > /dev/null 2>&1
fi
if blkid | grep xfs > /dev/null 2>&1;
	then xfs_growfs -d / > /dev/null 2>&1
fi
}

chk_mmcblk(){
fsck.fat -trawl /dev/mmcblk0p1 > /dev/null 2>&1
}

chk_mmcblk1(){
fsck.fat -trawl /dev/mmcblk1p1 > /dev/null 2>&1
}

chk_sda(){
fsck.fat -trawl /dev/sda1 > /dev/null 2>&1
}

chk_nvme(){
fsck.fat -trawl /dev/nvme0n1p1 > /dev/null 2>&1
}

### Grow Partition
if touch -c /dev/mmcblk0 2>/dev/null; then grow_mmcblk;
        else : &>/dev/null;
fi

if touch -c /dev/mmcblk1 2>/dev/null; then grow_mmcblk1;
        else : &>/dev/null;
fi

if touch -c /dev/sda 2>/dev/null; then grow_sda;
        else : &>/dev/null;
fi
if touch -c /dev/nvme0 2>/dev/null; then grow_nvme;
        else : &>/dev/null;
fi

### Fsck boot partition
umount /boot
sleep 1s
if touch -c /dev/mmcblk0 2>/dev/null; then chk_mmcblk;
        else : &>/dev/null;
fi

if touch -c /dev/mmcblk1 2>/dev/null; then chk_mmcblk1;
        else : &>/dev/null;
fi

if touch -c /dev/sda 2>/dev/null; then chk_sda;
        else : &>/dev/null;
fi
if touch -c /dev/nvme0 2>/dev/null; then chk_nvme;
        else : &>/dev/null;
fi
sleep 1s
mount /boot

### Clean up
systemctl disable firstboot > /dev/null 2>&1
update-rc.d firstboot remove > /dev/null 2>&1
rm -f /var/cache/debconf/*
rm -f /boot/rename_to_credentials.txt > /dev/null 2>&1
rm -f /usr/local/sbin/firstboot
exit 0
