#!/bin/bash
source /boot/username.txt
source /etc/opt/soc.txt

bcm2711_user(){
adduser ${user} --gecos ${user^} --disabled-password
echo "${user}:${passwd}" | chpasswd
adduser ${user} sudo
adduser ${user} audio
adduser ${user} dialout
adduser ${user} video
adduser ${user} disk
adduser ${user} spi
adduser ${user} i2c
adduser ${user} gpio
adduser ${user} plugdev
adduser ${user} netdev
adduser ${user} bluetooth
adduser ${user} input
adduser ${user} tty
}

bcm2710_user(){
adduser ${user} --gecos ${user^} --disabled-password
echo "${user}:${passwd}" | chpasswd
adduser ${user} sudo
adduser ${user} audio
adduser ${user} dialout
adduser ${user} video
adduser ${user} disk
adduser ${user} spi
adduser ${user} i2c
adduser ${user} gpio
adduser ${user} plugdev
adduser ${user} netdev
adduser ${user} bluetooth
adduser ${user} input
adduser ${user} tty
}

user_skins(){
mkdir -p /home/${user}/.config/mc
mv -f /etc/opt/user-ini /home/${user}/.config/mc/ini
mv -f /etc/opt/nanorc-user /home/${user}/.nanorc
chown -R ${user}:${user} /home/${user}
}

create_sudoers(){
rm -f /etc/sudoers.d/010_pi-nopasswd
tee /etc/sudoers.d/010_${user}-nopasswd <<EOF
${user} ALL=(ALL) NOPASSWD: ALL
EOF
}

case `grep -Fx "bcm2711" "/etc/opt/soc.txt" >/dev/null; echo $?` in
  0)
	bcm2711_user
	create_sudoers
	user_skins
    ;;
esac
case `grep -Fx "bcm2710" "/etc/opt/soc.txt" >/dev/null; echo $?` in
  0)
	bcm2710_user
	create_sudoers
	user_skins
    ;;
esac

rm -f /boot/username.txt
rm -f /usr/local/bin/whogoesthere
