#!/bin/bash

GCC=`ls -ls /usr/bin/gcc | sed 's/.*\(..\)/\1/' | sed 's/ //g'`

NAME=""
USERNAME=""
PASSWORD=""
LOCALE="en_US.UTF-8"
TIMEZONE="America/New_York"
USER_NAMESERVER1="8.8.8.8"
USER_NAMESERVER2="8.8.4.4"
if [ -f profile.txt ]; then
	. profile.txt
fi
rootpasswd="0"
VERSION="5.15.y"
BUILD_VERSION="1"
menuconfig="0"
crosscompile="1"
GCC_VERSION="gcc-$GCC"
gcc="1"
ccache="0"
clang="0"
DISTRO="debian"
DISTRO_VERSION="bullseye"
networkmanager="0"
ext4="1"
btrfs="0"
xfs="0"
custom_defconfig="0"
MYCONFIG=""
verbose="0"
devrootfs="1"
compress_img="0"
uscripts="0"
useracct="0"

# open fd
exec 3>&1

# store data to $VALUES variable
VALUES=$(dialog --ok-label "Submit" --no-cancel \
	  --backtitle "RASPBERRY PI IMAGE BUILDER" \
	  --title "" \
	  --form "" \
0 36 0 \
	"Name:"			1 1	"$NAME" 		1 7 23 0 \
	"Username:"		2 1	"$USERNAME" 		2 11 19 0 \
	"Password:"		3 1	"$PASSWORD"  		3 11 19 0 \
	"Enable root:"		4 1	"$rootpasswd"  		4 14 2 0 \
	""			5 1	""	 		5 14 0 0 \
	"Linux kernel"		6 1	""	 		6 14 0 0 \
        "Branch:"   		7 1     "$VERSION"        	7 9 7 0 \
        "Build:"   		8 1     "$BUILD_VERSION"        8 8 4 0 \
	"Menuconfig:"		9 1	"$menuconfig"  		9 13 2 0 \
	"Crosscompile:" 	10 1	"$crosscompile" 	10 15 2 0 \
	""			11 1	""	 		11 14 0 0 \
	"Compiler"		12 1	""	 		12 14 0 0 \
	"Version:"		13 1	"$GCC_VERSION"	 	13 10 8 0 \
	"GCC:"			14 1	"$gcc"		 	14 9 2 0 \
	"Ccache:"		15 1	"$ccache"	 	15 9 2 0 \
	"Clang:"		16 1	"$clang"	 	16 9 2 0 \
	""			17 1	""	 		17 14 0 0 \
	"Distribution"		18 1	""	 		18 14 0 0 \
	"Distro:"		19 1	"$DISTRO"	  	19 9 21 0 \
	"Release:"		20 1	"$DISTRO_VERSION"  	20 10 20 0 \
	"Network Manager:" 	21 1	"$networkmanager" 	21 18 2 0 \
	""			22 1	""	 		22 14 0 0 \
	"Filesystem"		23 1	""	 		23 14 0 0 \
	"EXT4:"			24 1	"$ext4"		 	24 8 2 0 \
	"BTRFS:"		25 1	"$btrfs"	 	25 8 2 0 \
	"XFS:"			26 1	"$xfs"		 	26 8 2 0 \
	""			27 1	""	 		27 14 0 0 \
	"Customize"		28 1	""	 		28 14 0 0 \
	"Defconfig:"		29 1	"$custom_defconfig" 	29 12 2 0 \
	"Name:"			30 1	"$MYCONFIG"	  	30 7 23 0 \
	""			31 1	""	 		31 14 0 0 \
	"User options"		32 1	""	 		32 14 0 0 \
	"Verbosity:"		33 1	"$verbose"		33 12 2 0 \
	"Devel Rootfs:"		34 1	"$devrootfs"		34 15 2 0 \
	"Compress img:"		35 1	"$compress_img" 	35 15 2 0 \
	"User scripts:"		36 1	"$uscripts"		36 15 2 0 \
	"User service:" 	37 1	"$useracct"		37 15 2 0 \
2>&1 1>&3)

# close fd
exec 3>&-

# convert into variables
echo "$VALUES" > tmp1
echo NAME='"' > tmp0
echo USERNAME='"' >> tmp0
echo PASSWORD='"' >> tmp0
echo rootpasswd= >> tmp0
echo VERSION='"' >> tmp0
echo BUILD_VERSION='"' >> tmp0
echo menuconfig= >> tmp0
echo crosscompile= >> tmp0
echo GCC_VERSION='"' >> tmp0
echo gcc= >> tmp0
echo ccache= >> tmp0
echo clang= >> tmp0
echo DISTRO='"' >> tmp0
echo DISTRO_VERSION='"' >> tmp0
echo networkmanager= >> tmp0
echo ext4= >> tmp0
echo btrfs= >> tmp0
echo xfs= >> tmp0
echo custom_defconfig= >> tmp0
echo MYCONFIG='"' >> tmp0
echo verbose= >> tmp0
echo devrootfs= >> tmp0
echo compress_img= >> tmp0
echo uscripts= >> tmp0
echo useracct= >> tmp0
echo USER_PKGS='"''"' >> tmp0
echo CLANG_LLVM='"'LLVM=1 LLVM_IAS=1'"' >> tmp0
echo lto_clang_thin=0 >> tmp0
echo CORES=\`nproc\` >> tmp0
echo CFLAGS='"''"' >> tmp0
echo KBUSER='"'$USER'"' >> tmp0
echo KBHOST='"'raspberrypi'"' >> tmp0
echo "set_locales(){" >> tmp0
echo "apt install -y locales" >> tmp0
echo "export LANGUAGE=${LOCALE}" >> tmp0
echo "export LANG=${LOCALE}" >> tmp0
echo "export LC_ALL=C.UTF-8" >> tmp0
echo "locale-gen ${LOCALE}" >> tmp0
echo "}" >> tmp0
echo "set_timezone(){" >> tmp0
echo "ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime" >> tmp0
echo "echo -n '${TIMEZONE}' > /etc/timezone" >> tmp0
echo "}" >> tmp0
echo NAMESERVER1='"'${USER_NAMESERVER1}'"' >> tmp0
echo NAMESERVER2='"'${USER_NAMESERVER2}'"' >> tmp0
echo rtl8812au=0 >> tmp0
echo rtl88x2bu=0 >> tmp0
echo rtl8811cu=0 >> tmp0
echo builder=5.0 >> tmp0
echo '"' > tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo >> tmp2
echo >> tmp2
echo '"' >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo _defconfig'"' >> tmp2
paste -d '\0' tmp0 tmp1 tmp2  > userdata.txt
rm -f tmp0 tmp1 tmp2

# categories
sed -i '5i### LINUX KERNEL' userdata.txt
sed -i '10i### COMPILER' userdata.txt
sed -i '15i### DISTRIBUTION' userdata.txt
sed -i '19i### FILESYSTEM' userdata.txt
sed -i '23i### CUSTOM' userdata.txt
sed -i '32i### CLANG/LLVM' userdata.txt
sed -i '35i### COMPILER TUNING' userdata.txt
sed -i '38i### WHOAMI AND HOST' userdata.txt
sed -i '41i### LOCALES' userdata.txt
sed -i '49i### TIMEZONE' userdata.txt
sed -i '54i### NAME SERVER' userdata.txt
sed -i '57i### EXTRA WIRELESS' userdata.txt
sed -i '61i### DO NOT EDIT BELOW THIS LINE' userdata.txt

# clear screen
clear -x

# userdata
if [[ -f "userdata.txt" ]]; then
	echo -e "userdata file created."
	exit 0
fi

exit 0
