#!/bin/bash

source lib/boards/$1
source userdata.txt
source custom.txt
MAKE_OUTPUT="output/$1"
BTITLE=`echo $FAMILY: $MOTD: $BOARD: $ARCH_EXT | sed 's/bcm2711v7/bcm2711/g' | sed -e 's/\(.*\)/\U\1/'`
if [[ "$BOARD" == "bcm2708" ]]; then
	TITLE=`echo $MOTD $BOARD | sed 's/bcm2708/Zero\/W\/1/g'`;
fi
if [[ "$BOARD" == "bcm2709" ]]; then
	TITLE=`echo $MOTD $BOARD | sed 's/bcm2709/ZeroW2\/2\/3/g'`;
fi
if [[ "$BOARD" == "bcm2710" ]]; then
	TITLE=`echo $MOTD $BOARD | sed 's/bcm2710/ZeroW2\/3/g'`;
fi
if [[ "$BOARD" == "bcm2711" ]]; then
	TITLE=`echo $MOTD $BOARD | sed 's/bcm2711/ZeroW2\/3\/4\/400\/5/g'`;
fi
if [[ "$BOARD" == "bcm2711v7" ]]; then
	TITLE=`echo $MOTD $BOARD | sed 's/bcm2711v7/4\/400/g'`;
fi
if [[ "$BOARD" == "bcm2712" ]]; then
	TITLE=`echo $MOTD $BOARD | sed 's/bcm2712/5/g'`;
fi
DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

while true; do
	exec 3>&1
	selection=$(dialog \
	--backtitle "$BTITLE" \
	--title "$TITLE" \
	--clear \
	--cancel-label "Exit" \
	--menu "Select:" $HEIGHT $WIDTH 0 \
	"1" "Make All ..."\
	"2" "Make Linux Kernel" \
	"3" "Make Root Filesystem" \
	"4" "Make Flashable Image" \
	2>&1 1>&3)
	exit_status=$?
	exec 3>&-;
case $exit_status in
	$DIALOG_CANCEL)
		clear -x
		echo "Program terminated."
		exit
		;;
	$DIALOG_ESC)
		clear -x
		echo "Program aborted." >&2
		exit 1
		;;
esac
case $selection in
	0 )
		clear -x
		echo "Program terminated."
		;;
	1 )
		make "all" "board=$1"
		dialog --prgbox "Results:" "ls $IMG_EXP ${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}* $MAKE_OUTPUT/" 30 75
		exit 0
		;;
	2 )
		make "kernel" "board=$1"
		dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.deb" 30 75
		;;
	3 )
		make "rootfs" "board=$1"
		dialog --prgbox "Results:" "ls ${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}*" 30 75
		;;
	4 )
		make "image" "board=$1"
		dialog --prgbox "Results:" "ls $IMG_EXP" 30 75
		;;
esac
done
