#!/bin/bash
COUNT=0

# userdata-txt
source lib/source
UD=userdata.txt
userdata(){
echo ""
echo "Create a userdata.txt file"
while [ true ]; do
	read -t 10 -n 1
	if [ $? = 0 ]; then
		exit 0;
	fi
done
}

if [ -f "$UD" ]; then
	:;
else 
	userdata;
fi
validation

# menu list
while IFS=$'\n' read -r opt; do
    COUNT=$(( COUNT+1 ))
    options+=($COUNT "$opt" off)
done < lib/dialog/list

# dialog menu
cmd=(dialog --backtitle "Raspberry Pi Image Builder" --title "B O A R D S" --cancel-label "Exit" --radiolist "" 0 0 0)
choices=($("${cmd[@]}" "${options[@]}" 2>&1 1>/dev/tty))

# selection
for choice in "${choices[@]}"; do
	source lib/dialog/names
	boardnames
	chmod +x lib/dialog/general
	./lib/dialog/general $BOARD
done

# finish
clear -x
echo -e "Program terminated."
exit 0
