#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armel"
DEBARCH="${ARCH_EXT}"
KERNEL_VAR="kernel"
CROSS_COMPILE="arm-linux-gnueabi-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# menu
PRETTY_BOARD="Raspberry Pi Zero/W/1		BCM2708 / ARMEL"

# misc
FAMILY="broadcom"
FAMILY_EXT=""

# default config
LINUX_DEFCONFIG="bcmrpi_defconfig"

# partitions
IMG_OFFSET="4MiB"
P_VALUE="p2"

# output
BOARD="bcm2708"
BOARD_EXT="rpi"
OUTPUT="output/${BOARD}"
IMG_EXP="${BOARD_EXT}-*.img*"

# cmdline
CONSOLE="console=serial0,115200 console=tty1"
EXTRA="loglevel=5 net.ifnames=0 firmware_class.path=/lib/firmware/updates/brcm"

# Serial
DEVUAN_SERIAL="T0:23:respawn:/sbin/getty -L serial0 115200 vt100"

# packaging
KERNEL_IMG="kernel.img"
SERIES="bcm2708-${BOARD_EXT}"
