#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
KERNEL_VAR="kernel7l"
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# menu
PRETTY_BOARD="Raspberry Pi 4/400		BCM2711 / ARMHF"

# misc
FAMILY="broadcom"
FAMILY_EXT=""

# default config
LINUX_DEFCONFIG="bcm2711_defconfig"

# partitions
IMG_OFFSET="4MiB"
P_VALUE="p2"

# output
BOARD="bcm2711v7"
BOARD_EXT="rpi-4"
OUTPUT="output/${BOARD}"
IMG_EXP="${BOARD_EXT}-*.img*"

# cmdline
CONSOLE="console=serial0,115200 console=tty1"
EXTRA="loglevel=5 net.ifnames=0"

# Serial
DEVUAN_SERIAL="T0:23:respawn:/sbin/getty -L serial0 115200 vt100"

# packaging
KERNEL_IMG="kernel7l.img"
SERIES="bcm2711-rpi"
