#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
KERNEL_VAR="kernel7"
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# menu
PRETTY_BOARD="Raspberry Pi ZeroW2/2/3		BCM2709    ARMHF"

# misc
FAMILY="broadcom"
FAMILY_EXT=""

# default config
LINUX_DEFCONFIG="bcm2709_defconfig"

# partitions
IMG_OFFSET="4MiB"
P_VALUE="p2"

# output
BOARD="bcm2709"
BOARD_EXT="rpi-2+3"
OUTPUT="output/${BOARD}"
IMG_EXP="${BOARD_EXT}-*.img*"

# cmdline
CONSOLE="console=serial0,115200 console=tty1"
EXTRA="loglevel=5 net.ifnames=0"

# Serial
DEVUAN_SERIAL="T0:23:respawn:/sbin/getty -L serial0 115200 vt100"

# packaging
KERNEL_IMG="kernel7.img"
SERIES="bcm2709-rpi"
