#!/bin/bash
### BEGIN INIT INFO
# Provides: actled
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop:
# Short-Description: Turns off activity led
# Description:
### END INIT INFO

# chmod +x /etc/init.d/actled
# update-rc.d actled defaults 2

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Turning off activity led"
    /usr/local/sbin/actled 2>/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac