#!/bin/bash
### BEGIN INIT INFO
# Provides: bthelper
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop:
# Short-Description: Raspberry Pi bluetooth helper
# Description:
### END INIT INFO

# chmod +x /etc/init.d/bthelper
# update-rc.d bthelper defaults 2

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Raspberry Pi bluetooth helper"
    /usr/bin/btuart 2>/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
