#!/bin/bash
### BEGIN INIT INFO
# Provides: credentials
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop: 0 6
# Short-Description: Input wifi information on firstboot
# Description:
### END INIT INFO

# chmod +x /etc/init.d/credentials
# update-rc.d credentials defaults 2

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Checking credentials"
    /usr/local/bin/credentials 2>/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac