#!/bin/bash
### BEGIN INIT INFO
# Provides: firstboot
# Required-Start: checkfs checkroot-bootclean mountall $local_fs
# Required-Stop:
# Default-Start: S
# Default-Stop:
# Short-Description: Expands the root partition
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

# chmod +x /etc/init.d/firstboot
# update-rc.d firstboot defaults S

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting firstboot"
    /usr/local/sbin/firstboot 2>/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac