#!/bin/bash
### BEGIN INIT INFO
# Provides: governor
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop:
# Short-Description: Set governor
# Description:
### END INIT INFO

# chmod +x /etc/init.d/governor
# update-rc.d governor defaults 2

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Set governor"
    /usr/local/bin/governor -r 2>/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
