#!/bin/bash
### System Setup Script
echo Running System Setup.
sleep 1s
sudo dpkg-reconfigure locales tzdata keyboard-configuration
### Clear Motd
echo Cleaning motd.
sleep 1s
sudo rm -f /etc/motd
sudo mv -f /etc/new.motd /etc/motd
echo Done.
sleep 1s
echo
echo System is ready to go.
sudo rm -f /usr/local/bin/run-setup
