#!/bin/bash
source /boot/username.txt

### FUNCTIONS
create_user(){
adduser ${user} --gecos ${user^} --disabled-password
echo "${user}:${passwd}" | chpasswd
adduser ${user} sudo
adduser ${user} audio
adduser ${user} dialout
adduser ${user} video
adduser ${user} disk
adduser ${user} spi
adduser ${user} i2c
adduser ${user} gpio
adduser ${user} plugdev
adduser ${user} netdev
adduser ${user} bluetooth
adduser ${user} input
adduser ${user} tty
}

create_sudoers(){
rm -f /etc/sudoers.d/010_pi-nopasswd
tee /etc/sudoers.d/010_${user}-nopasswd <<EOF
${user} ALL=(ALL) NOPASSWD: ALL
EOF
}

user_skins(){
mkdir -p /home/${user}/.config/mc
mv -f /etc/opt/user-ini /home/${user}/.config/mc/ini
mv -f /etc/opt/nanorc-user /home/${user}/.nanorc
chown -R ${user}:${user} /home/${user}
}

### RUN
create_user
create_sudoers
user_skins
rm -f /boot/username.txt
rm -f /usr/local/bin/whogoesthere
exit 0
