#!/bin/bash
source lib/source.txt
source lib/func.txt
source lib/rpi3_func.txt
source userdata.txt
RED="\e[1;31m"
FIN="\e[0m"
UD=userdata.txt

userdata () {
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please review the README.md or run make config." 3 51
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found."
else 
    userdata
fi

case `grep -Fx "devuser=1" "userdata.txt" >/dev/null; echo $?` in
  0)
    echo ""
    echo -e "${RED}Wrong userdata file!${FIN}"
    echo ""
    while [ true ] ; do
    read -t 2 -n 1
    if [ $? = 0 ] ; then
    exit ;
    else
    dialog --infobox "Please review the README.md or run make config." 3 51
    fi
    done
    ;;
  *)
    #
    ;;
esac

mkdir -p ${TMP3}
cd ${TMP3}

### Download kernel
download

### Extract
extract

### Setup
case `grep -Fx "edge=1" "../userdata.txt" >/dev/null; echo $?` in
  0)
    edgev8_setup
    ;;
  1)
    armv8_setup
    ;;
  *)
    #
    ;;
esac

### Patching
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ccpatch
    ;;
  1)
    ncpatch
    ;;
  *)
    #
    ;;
esac

### Defconfig
case `grep -Fx "custom_defconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv8_cconfig
    ;;
  1)
    rpi3_fconfig
    ;;
  *)
    #
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv8_menuconfig
    ;;
  *)
    #
    ;;
esac

### Build deb
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv8_ccompile
    ;;
  1)
    armv8_ncompile
    ;;
  *)
    #
    ;;
esac
echo
cd ..
rm -f linux-libc-dev*.deb
rm -f *.buildinfo
rm -f *.changes
echo Done.
