#!/bin/bash
# depends: curl
source lib/function/echoes

echo "Example: 5.15"
echo
echo -en "${WHT}Select branch: ${FIN}"
read branch

if [[ `wget -S --spider https://raw.githubusercontent.com/raspberrypi/linux/rpi-$branch.y/Makefile 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	curl --silent -L https://raw.githubusercontent.com/raspberrypi/linux/rpi-$branch.y/Makefile | grep -m1 VERSION
	curl --silent -L https://raw.githubusercontent.com/raspberrypi/linux/rpi-$branch.y/Makefile | grep -m1 PATCHLEVEL
	curl --silent -L https://raw.githubusercontent.com/raspberrypi/linux/rpi-$branch.y/Makefile | grep -m1 SUBLEVEL
	curl --silent -L https://raw.githubusercontent.com/raspberrypi/linux/rpi-$branch.y/Makefile | grep -m1 EXTRAVERSION
else
	echo ""
	echo -e "The branch you selected is not available."
	exit 0
fi

exit 0
