#!/bin/bash
source userdata.txt > /dev/null 2>&1;
source lib/function/echoes
source lib/source
UD=userdata.txt

userdata(){
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    :;
else 
    userdata
fi

validation

if `grep -Fx 'DISTRO="debian"' "userdata.txt" >/dev/null;`
	then make debianos;
fi
if `grep -Fx 'DISTRO="devuan"' "userdata.txt" >/dev/null;`
	then make devuanos;
fi
if `grep -Fx 'DISTRO="ubuntu"' "userdata.txt" >/dev/null;`
	then make ubuntuos;
fi