#!/bin/bash
source userdata.txt > /dev/null 2>&1;
UD=userdata.txt

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found."
else 
    userdata
fi
if `grep -Fx "debian=1" "userdata.txt" >/dev/null;`
	then make debianos;
fi
if `grep -Fx "devuan=1" "userdata.txt" >/dev/null;`
	then make devuanos;
fi
if `grep -Fx "ubuntu=1" "userdata.txt" >/dev/null;`
	then make ubuntuos;
fi