#!/bin/bash
source userdata.txt

if `grep -Fx "debian=1" "userdata.txt" >/dev/null;`
	then make debianos;
fi
if `grep -Fx "devuan=1" "userdata.txt" >/dev/null;`
	then make devuanos;
fi
if `grep -Fx "ubuntu=1" "userdata.txt" >/dev/null;`
	then make ubuntuos;
fi