#!/bin/bash

# cleanup
umount p2/proc p2/sys p2/dev p2/run > /dev/null 2>&1
umount sysroot/proc sysroot/sys sysroot/dev/pts sysroot/dev sysroot/run > /dev/null 2>&1
umount -l p1 p2 sysroot > /dev/null 2>&1
rm -fdr p1 p2 img sysroot > /dev/null 2>&1
rm -f {part-uuid.txt,kernel.txt,kpart*,gcc.txt,ccache.txt,clang.txt}
losetup -d /dev/loop* > /dev/null 2>&1
sleep 1s
losetup -d /dev/loop* > /dev/null 2>&1
echo -e "[ DONE ]"
exit 0
