#!/bin/bash
source lib/function/universal
source lib/function/devuan
source lib/function/boot
source lib/function/echoes
source lib/source
source userdata.txt > /dev/null 2>&1
UD=userdata.txt

userdata(){
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 20 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    :;
else 
    userdata
fi

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then set -eux -o pipefail;
	else set -eu -o pipefail;
fi
if ls /usr/bin/toilet > /dev/null 2>&1
	then toilet -f small --filter metal 'Raspberry Pi';
	else echo -e "${RED}Raspberry Pi Image Builder${FIN}";
fi
RAM=0
PROXY=""
IMAGE_FOLDER="img/"
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then DEVICE_SOC="rpi-4";
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then DEVICE_SOC="rpi-3";
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then DEVICE_SOC="rpi";
fi
IMAGE_DATE="$(date +%F)"
IMAGE_FILE_NAME="${DEVICE_SOC}-devuan-${DISTRO_VERSION}-${IMAGE_DATE}.img"
if [ $RAM -ne 0 ]; then
	IMAGE_FOLDER="ram/"
fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then
	mount -t tmpfs -o size=3G tmpfs $IMAGE_FOLDER
fi

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then image_size;
	else image_size > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partition_uuid;
	else partition_uuid > /dev/null 2>&1;
fi

### cmd line
echo && echo
echo -e -n "${RED}Setting up boot directory${FIN}."
cmdline > /dev/null 2>&1
if ls p1/cmdline.txt > /dev/null 2>&1
	then echo && echo -n "cmdline.txt " && sleep 1s && echo_nok;
	else echo && echo -n "cmdline.txt " && sleep 1s && echo_fail && exit;
fi
### config dot txt
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then bcm2711_config > /dev/null 2>&1;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then bcm2710_config > /dev/null 2>&1;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then bcm2708_config > /dev/null 2>&1;
fi
if ls p1/config.txt > /dev/null 2>&1
	then echo && echo -n "config.txt  " && sleep 1s && echo_nok;
	else echo && echo -n "config.txt  " && sleep 1s && echo_fail && exit;
fi
bcm2708_initrd
### extract rootfs
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then aarch64_rootfs;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then aarch64_rootfs;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then armel_rootfs;
fi

mkdir -p p2/etc/apt/apt.conf.d p2/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "p2/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"

# qemu static
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then qemu_arm64;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then qemu_arm64;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then qemu_arm;
fi

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then distro_release;
	else distro_release > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then create_fstab;
	else create_fstab > /dev/null 2>&1;
fi

if [ -n "$PROXY" ] ; then
	tee "p2/etc/apt/apt.conf.d/30proxy" <<EOF
Acquire::http::proxy "http://127.0.0.1:3142";
EOF
fi

# setup stage2
cp scripts/devuan-stage2 p2/root
cp lib/function/devuan p2/root/devuan.txt
cp lib/function/universal p2/root/universal.txt
cp lib/source p2/root/source.txt
cp userdata.txt p2/root
cp soc.txt p2/root
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then cp output/bcm2711/*.deb p2/root;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then cp output/bcm2710/*.deb p2/root;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then cp output/bcm2708/*.deb p2/root;
fi
cp files/devuan/misc/* p2/root
cp files/devuan/patches/* p2/root
cp files/devuan/rules/* p2/root
cp files/devuan/scripts/* p2/root
cp files/misc/* p2/root
cp files/scripts/* p2/root
cp files/users/* p2/root
cp firmware/{fw-0a5c_21e8.hcd,UPDATE.mem} p2/root
if `grep -Fx "userscripts=1" "userdata.txt" >/dev/null;`
	then uscripts_stage1;
fi
echo -e "${RED}Starting chroot${FIN} ..."
# Mount and chroot
mount -o bind p1 p2/boot
mount -o bind /dev p2/dev
mount -o bind /dev/pts p2/dev/pts
chroot p2 /root/devuan-stage2
# unmount
umount p2/dev/pts
umount p2/dev
umount p2/boot

# qemu remove static
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then qemu_arm64_remove;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then qemu_arm64_remove;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then qemu_arm_remove;
fi
cp -f p2/root/kernel.txt .
rm p2/root/devuan-stage2
rm -f p2/root/*.txt
rm -f p2/var/cache/debconf/*

if [ -n "$PROXY" ] ; then
	rm p2/etc/apt/apt.conf.d/30proxy
fi
rm p2/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io

### Finish
defrag_p2

umount p2
umount p1

losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then
	umount "${IMAGE_FOLDER}"
fi
rmdir "${IMAGE_FOLDER}"
rmdir p1 p2

if `grep -Fx "ext4=1" "userdata.txt" >/dev/null;`
	then ext4_shrink;
fi
if `grep -Fx "btrfs=1" "userdata.txt" >/dev/null;`
	then : ;
fi

if `grep -Fx "admin=1" "userdata.txt" >/dev/null;`
	then echo && echo_compress && compress_image && echo_done;
	else rename_image;
fi
rm -f part-uuid.txt soc.txt kernel.txt
