#!/bin/bash
source lib/devuan_func.txt
source lib/boot_func.txt
source lib/echo_func.txt
source lib/source.txt
source userdata.txt > /dev/null 2>&1
UD=userdata.txt

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 20 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found." > /dev/null 2>&1;
else 
    userdata
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then set -eux -o pipefail;
	else set -eu -o pipefail;
fi
if ls /usr/bin/toilet > /dev/null 2>&1
	then toilet -f small --filter metal 'Raspberry Pi';
	else echo -e "${RED}Raspberry Pi Image Builder${FIN}";
fi
RAM=0
PROXY=""
IMAGE_FOLDER="img/"
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then DEVICE_SOC="bcm2711";
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then DEVICE_SOC="bcm2710";
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then DEVICE_SOC="bcm2708";
fi
IMAGE_DATE="$(date +%F)"
IMAGE_FILE_NAME="${DEVICE_SOC}-devuan-${DISTRO_VERSION}-${IMAGE_DATE}.img"
if [ $RAM -ne 0 ]; then
	IMAGE_FOLDER="ram/"
fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then
	mount -t tmpfs -o size=3G tmpfs $IMAGE_FOLDER
fi

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partitions;
	else partitions > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partition_uuid;
	else partition_uuid > /dev/null 2>&1;
fi

### cmd line
echo && echo
echo -e -n "${RED}Installing boot bits${FIN}."
cmdline > /dev/null 2>&1
if ls p1/cmdline.txt > /dev/null 2>&1
	then echo && echo -n "cmdline.txt " && sleep 1s && echo_nok;
	else echo && echo -n "cmdline.txt " && sleep 1s && echo_fail && exit;
fi
### config dot txt
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then bcm2711_config > /dev/null 2>&1;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then bcm2710_config > /dev/null 2>&1;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then bcm2708_config > /dev/null 2>&1;
fi
if ls p1/config.txt > /dev/null 2>&1
	then echo && echo -n "config.txt " && sleep 1s && echo_nok;
	else echo && echo -n "config.txt " && sleep 1s && echo_fail && exit;
fi
### Fetching boot bits
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then rpi4_bootbins;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then rpi_bootbins;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then rpi_bootbins;
fi

### clean boot bits
rm -f firmware/boot/*

### extract rootfs
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then aarch64_rootfs;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then aarch64_rootfs;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then armel_rootfs;
fi

mkdir -p p2/etc/apt/apt.conf.d p2/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "p2/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"

mkdir -p p2/usr/bin
cp $(which "qemu-aarch64-static") p2/usr/bin

distro_release(){
case `grep -Fx 'DISTRO_VERSION="testing"' "userdata.txt" >/dev/null; echo $?` in
  0)
tee p2/etc/apt/sources.list <<EOF
deb http://deb.devuan.org/merged ${DISTRO_VERSION} main contrib non-free
EOF
    ;;
  1)
tee p2/etc/apt/sources.list <<EOF
deb http://deb.devuan.org/merged ${DISTRO_VERSION} main contrib non-free
deb http://deb.devuan.org/merged ${DISTRO_VERSION}-updates main contrib non-free
deb http://deb.devuan.org/merged ${DISTRO_VERSION}-security main contrib non-free
deb http://deb.devuan.org/merged ${DISTRO_VERSION}-backports main contrib non-free
EOF
   ;;
esac
}

create_fstab(){
tee p2/etc/fstab <<EOF
UUID=${BOOT_UUID}	/boot		vfat    defaults 0 2
UUID=${ROOT_UUID}	/		ext4	defaults,noatime,nodiratime,commit=600,errors=remount-ro 0 1
tmpfs	/tmp		tmpfs	defaults,nosuid 0 0
EOF
}

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then distro_release;
	else distro_release > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then create_fstab;
	else create_fstab > /dev/null 2>&1;
fi

if [ -n "$PROXY" ] ; then
	tee "p2/etc/apt/apt.conf.d/30proxy" <<EOF
Acquire::http::proxy "http://127.0.0.1:3142";
EOF
fi

# setup stage2
cp scripts/devuan-stage2 p2/root
cp lib/devuan_func.txt p2/root
cp lib/universal_func.txt p2/root
cp lib/source.txt p2/root
cp userdata.txt p2/root
cp soc.txt p2/root
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then cp output/bcm2711/*.deb p2/root;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then cp output/bcm2710/*.deb p2/root;
fi
if `grep -Fx "bcm2708" "soc.txt" >/dev/null;`
	then cp output/bcm2708/*.deb p2/root;
fi
cp files/devuan/misc/* p2/root
cp files/devuan/patches/* p2/root
cp files/devuan/rules/* p2/root
cp files/devuan/scripts/* p2/root
cp files/misc/* p2/root
cp files/scripts/* p2/root
cp files/users/* p2/root
cp firmware/fw-0a5c_21e8.hcd p2/root
echo -e "${RED}Starting chroot${FIN} ..."
# Mount and chroot
mount -o bind p1 p2/boot
mount -o bind /dev p2/dev
mount -o bind /dev/pts p2/dev/pts
chroot p2 /root/devuan-stage2
# unmount
umount p2/dev/pts
umount p2/dev
umount p2/boot

rm p2/usr/bin/qemu-aarch64-static
rm p2/root/devuan-stage2
rm p2/root/devuan_func.txt
rm p2/root/universal_func.txt
rm p2/root/source.txt
rm p2/root/userdata.txt
rm p2/root/soc.txt
rm -f p2/var/cache/debconf/*

if [ -n "$PROXY" ] ; then
	rm p2/etc/apt/apt.conf.d/30proxy
fi
rm p2/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io

### Finish
e4defrag -c p2

umount p2
umount p1

losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then
	umount "${IMAGE_FOLDER}"
fi
rmdir "${IMAGE_FOLDER}"
rmdir p1 p2
rm -f part-uuid.txt soc.txt
