#!/bin/bash
source lib/function/echoes

docker_makefile(){
cp -f Makefile Makefile.orig
sed -i 's/sudo //g' Makefile
}

dmakefile(){
if ls Makefile > /dev/null 2>&1
	then docker_makefile;
	else echo -e "${RED}Please review the Docker Wiki or README.md${FIN}${WHT}.${FIN}" && exit;
fi
}

run_check(){
if ls Makefile.orig > /dev/null 2>&1
	then echo -e "${YLW}You have already run this command${FIN}${WHT}!${FIN}" && exit;
fi
}

sleep 1s
run_check
dmakefile
echo_done