#!/bin/bash
URL="https://github.com/pyavitz/rpi-img-builder/releases/download/linux/"
DOWNLOAD="aria2c -c --download-result=hide --console-log-level=error --disable-ipv6=true --summary-interval=0 --show-files=false"
VERSION="5.10.y"
RED="\e[1;31m"
HELP="\e[1;33m"
GRN="\e[1;32m"
PNK="\e[1;35m"
WHT="\e[1;37m"
FIN="\e[0m"

echo_bdone(){
echo -e "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
}

rpi(){
echo
echo -e "${RED}Downloading${FIN} ..."
${DOWNLOAD} ${URL}rpi-${VERSION}.tar.xz && echo_bdone
echo
echo -e "${RED}Extracting archive${FIN} ..."
echo -e -n "${WHT}"
pv rpi-${VERSION}.tar.xz | tar -xJ rpi-${VERSION}
echo -e -n "${FIN}"
rm -f rpi-${VERSION}.tar.xz
if ls output/bcm2708 > /dev/null 2>&1
	then sudo rm -fdr output/bcm2708;
fi
mkdir -p output
mv rpi-${VERSION} output/bcm2708
echo
ls output/bcm2708/*.deb
echo -e "${RED}Done${FIN}."
}

rpi3(){
echo
echo -e "${RED}Downloading${FIN} ..."
${DOWNLOAD} ${URL}rpi3-${VERSION}.tar.xz && echo_bdone
echo
echo -e "${RED}Extracting archive${FIN} ..."
echo -e -n "${WHT}"
pv rpi3-${VERSION}.tar.xz | tar -xJ rpi3-${VERSION}
echo -e -n "${FIN}"
rm -f rpi3-${VERSION}.tar.xz
if ls output/bcm2710 > /dev/null 2>&1
	then sudo rm -fdr output/bcm2710;
fi
mkdir -p output
mv rpi3-${VERSION} output/bcm2710
echo
ls output/bcm2710/*.deb
echo -e "${RED}Done${FIN}."
}

rpi4(){
echo
echo -e "${RED}Downloading${FIN} ..."
${DOWNLOAD} ${URL}rpi4-${VERSION}.tar.xz && echo_bdone
echo
echo -e "${RED}Extracting archive${FIN} ..."
echo -e -n "${WHT}"
pv rpi4-${VERSION}.tar.xz | tar -xJ rpi4-${VERSION}
echo -e -n "${FIN}"
rm -f rpi4-${VERSION}.tar.xz
if ls output/bcm2711 > /dev/null 2>&1
	then sudo rm -fdr output/bcm2711;
fi
mkdir -p output
mv rpi4-${VERSION} output/bcm2711
echo
ls output/bcm2711/*.deb
echo -e "${RED}Done${FIN}."
}

if [ $# -eq 0 ]
then
        echo -e "\e[0;31mMissing options!${FIN}"
        echo "(run $0 -h for help)"
        echo ""
        exit 0
fi

ECHO="false"

while getopts "1234h" OPTION; do
        case $OPTION in

                1)
                        ECHO="rpi"
                        ;;
                3)
                        ECHO="rpi3"
                        ;;
                4)
                        ECHO="rpi4"
                        ;;
                h)                       
                        echo -e "${RED}Helper, downloads a binary Linux package${FIN}."
                        echo ""
                        echo -e "   make 2708        Raspberry Pi 0/1/W/B/+"
                        echo -e "   make 2710        Raspberry Pi 2/3/A/B/+"
                        echo -e "   make 2711        Raspberry Pi 4B"
                        echo ""
                        exit 0
                        ;;

        esac
done
if [ $ECHO = "rpi" ]
then
        rpi;
fi
if [ $ECHO = "rpi3" ]
then
        rpi3;
fi
if [ $ECHO = "rpi4" ]
then
        rpi4;
fi
