#!/bin/bash
source lib/source
source lib/function/gcc
source lib/function/kernel
source lib/function/echoes
source userdata.txt
UD=userdata.txt

userdata(){
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please review the README.md or run make config." 3 51
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    :;
else 
    userdata
fi

case `grep -Fx "devuser=1" "userdata.txt" >/dev/null; echo $?` in
  0)
    echo ""
    echo -e "${RED}Wrong userdata file${FIN}!"
    echo ""
    while [ true ] ; do
    read -t 2 -n 1
    if [ $? = 0 ] ; then
    exit ;
    else
    dialog --infobox "Please review the README.md or run make config." 3 51
    fi
    done
    ;;
esac

# prep
validation
gcc_version
source_dir
clean_source

### Download kernel
download

### Extract
extract

### Setup
if `grep -Fx "bcm2711" "../soc.txt" >/dev/null;`
	then armv8_setup && rpi4_binaries;
fi
if `grep -Fx "bcm2710" "../soc.txt" >/dev/null;`
	then armv8_setup && rpi_binaries;
fi
if `grep -Fx "bcm2708" "../soc.txt" >/dev/null;`
	then armv6_setup && rpi_binaries;
fi


### Patching
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ccpatch
    ;;
  1)
    ncpatch
    ;;
esac

### Defconfig
if `grep -Fx "bcm2711" "../../soc.txt" >/dev/null;`
	then choose_rpi4_defconfig;
fi
if `grep -Fx "bcm2710" "../../soc.txt" >/dev/null;`
	then choose_rpi3_defconfig;
fi
if `grep -Fx "bcm2708" "../../soc.txt" >/dev/null;`
	then choose_rpi_defconfig;
fi

### Menuconfig
if `grep -Fx "bcm2711" "../../soc.txt" >/dev/null;`
	then choose_v8_menuconfig;
fi
if `grep -Fx "bcm2710" "../../soc.txt" >/dev/null;`
	then choose_v8_menuconfig;
fi
if `grep -Fx "bcm2708" "../../soc.txt" >/dev/null;`
	then choose_v6_menuconfig;
fi

### Build deb
if `grep -Fx "bcm2711" "../../soc.txt" >/dev/null;`
	then choose_v8_compile;
fi
if `grep -Fx "bcm2710" "../../soc.txt" >/dev/null;`
	then choose_v8_compile;
fi
if `grep -Fx "bcm2708" "../../soc.txt" >/dev/null;`
	then choose_v6_compile;
fi
echo
cd ..
rm -f linux-libc-dev*.deb
rm -f *.buildinfo
rm -f *.changes
if `grep -Fx "bcm2711" "../soc.txt" >/dev/null;`
	then bcm2711_check && mkdir -p ${OUT4} && mv -f *.deb ${OUT4}/;
fi
if `grep -Fx "bcm2710" "../soc.txt" >/dev/null;`
	then bcm2710_check && mkdir -p ${OUT3} && mv -f *.deb ${OUT3}/;
fi
if `grep -Fx "bcm2708" "../soc.txt" >/dev/null;`
	then bcm2708_check && mkdir -p ${OUT} && mv -f *.deb ${OUT}/;
fi
echo_done
