#!/bin/bash
source userdata.txt
source lib/function/mainline
source lib/function/echoes
source lib/source
UD=userdata.txt

userdata () {
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please review the README.md or run make mlconfig." 3 53
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo -e "${YLW}$UD file found${FIN}."
else 
    userdata
fi

case `grep -Fx "rpiuser=1" "userdata.txt" >/dev/null; echo $?` in
  0)
    echo ""
    echo -e "${RED}Wrong userdata file${FIN}!"
    echo ""
    while [ true ] ; do
    read -t 2 -n 1
    if [ $? = 0 ] ; then
    exit ;
    else
    dialog --infobox "Please review the README.md or run make mlconfig." 3 53
    fi
    done
    ;;
esac

source_dir
mainline_clean

### Download kernel
case `grep -Fx "mainline=1" "../userdata.txt" >/dev/null; echo $?` in
  0)
    download_mainline
    ;;
  1)
    download_stable
    ;;
esac

### Clean kernel
#make clean
#make mrproper

### Patching
patching

### Defconfig
case `grep -Fx "custom_defconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    cconfig
    ;;
  1)
    rpi_config
    ;;
esac

### Menuconfig
if `grep -Fx "menuconfig=1" "../../userdata.txt" >/dev/null;`
    then menu_config
fi

### Build deb
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    cross_compile
    ;;
  1)
    native_compile
    ;;
esac
echo
cd ..
rm -f linux-libc-dev*.deb
rm -f *.buildinfo
rm -f *.changes
if `grep -Fx "bcm2711" "../soc.txt" >/dev/null;`
	then mkdir -p ${OUT4} && mv -f *.deb ${OUT4}/;
fi
echo_done
