#!/bin/bash
source kernel.txt
mkdir -p ${tmp4v7}
cd ${tmp4v7}

### Download kernel
echo
echo Downloading kernel.
wget -cq --show-progress https://github.com/raspberrypi/linux/archive/rpi-${version}.tar.gz
echo Done.

### Extract
echo
echo Extracting archive.
tar -xf rpi-${version}.tar.gz
#rm -f rpi-${version}.tar.gz #remove
echo Done.

### Setup
cd ${kernel}-${version}
export ARCH=arm
KERNEL=kernel7l

### Clean kernel
#make clean
#make mrproper

### Packaging patch
echo
echo Applying packaging patch.
patch -p1 < ../${pat}/rpi4b-v7-packaging.patch

### Foundation defconfig
case `grep -Fx "foundation_defconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
   make ARCH=arm bcm2711_defconfig
    ;;
  1)
    echo *
    echo ** foundation defconfig set to false
    ;;
  *)
    echo no config found!
    ;;
esac

### Builder defconfig
case `grep -Fx "lessfoundation_defconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    cp -f ../${def}/rpi4v7-noinitrd_defconfig arch/arm/configs/
    make ARCH=arm rpi4v7-noinitrd_defconfig
    ;;
  1)
    echo *
    echo ** lessfoundation defconfig set to false
    ;;
  *)
    echo no config found!
    ;;
esac

### Custom defconfig
case `grep -Fx "custom_defconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
   cp -f ../${def}/custom_defconfig arch/arm/configs/
   make ARCH=arm custom_defconfig
    ;;
  1)
    echo *
    echo ** custom defconfig set to false
    ;;
  *)
    echo no config found!
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
   echo
   echo Opening menuconfig.
   sleep 1s
   make menuconfig
    ;;
  1)
    echo ** menuconfig set to false
    ;;
  *)
    echo grumble! grumble!
    ;;
esac

### Build deb
echo
echo Building deb packages.
#make -j${cores} ARCH=arm bindeb-pkg # native
make -j${cores} ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bindeb-pkg
echo Done.
echo
