#!/bin/bash
source lib/source.txt
source lib/func.txt
source lib/rpi3_func.txt
source userdata.txt
UD=userdata.txt

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 20 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found."
else 
    userdata
fi

mkdir -p ${TMP3}
cd ${TMP3}

### Download kernel
download

### Extract
extract

### Setup
case `grep -Fx "edge=1" "../userdata.txt" >/dev/null; echo $?` in
  0)
    edgev8_setup
    ;;
  1)
    armv8_setup
    ;;
  *)
    #
    ;;
esac

### Patching
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ccpatch
    ;;
  1)
    ncpatch
    ;;
  *)
    #
    ;;
esac

### Defconfig
case `grep -Fx "custom_defconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv8_cconfig
    ;;
  1)
    rpi3_fconfig
    ;;
  *)
    #
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv8_menuconfig
    ;;
  *)
    #
    ;;
esac

### Build deb
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv8_ccompile
    ;;
  1)
    armv8_ncompile
    ;;
  *)
    #
    ;;
esac
echo Done.
echo
