#!/bin/bash
source lib/source.txt
source lib/func.txt
source lib/rpi3_func.txt
source userdata.txt

mkdir -p ${TMP3}
cd ${TMP3}

### Download kernel
DOWNLOAD

### Extract
EXTRACT

### Setup
SETUP

### Patching
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    CCPATCH
    ;;
  1)
    NCPATCH
    ;;
  *)
    #
    ;;
esac

### Defconfig
case `grep -Fx "custom_defconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ARMV8_CCONFIG
    ;;
  1)
    RPI3_FCONFIG
    ;;
  *)
    #
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ARMV8_MENUCONFIG
    ;;
  *)
    #
    ;;
esac

### Build deb
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ARMV8_CCOMPILE
    ;;
  1)
    ARMV8_NCOMPILE
    ;;
  *)
    #
    ;;
esac
echo Done.
echo
