#!/bin/bash
source lib/source.txt
source lib/func.txt
source lib/rpi_func.txt
source userdata.txt

mkdir -p ${TMP0}
cd ${TMP0}

### Download kernel
download

### Extract
extract

### Setup
case `grep -Fx "edge=1" "../userdata.txt" >/dev/null; echo $?` in
  0)
    edgev6_setup
    ;;
  1)
    armv6_setup
    ;;
  *)
    #
    ;;
esac

### Patching
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ccpatch
    ;;
  1)
    ncpatch
    ;;
  *)
    #
    ;;
esac

### Defconfig
case `grep -Fx "custom_defconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv6_cconfig
    ;;
  1)
    rpi_fconfig
    ;;
  *)
    #
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv6_menuconfig
    ;;
  *)
    #
    ;;
esac

### Build deb
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    armv6_ccompile
    ;;
  1)
    armv6_ncompile
    ;;
  *)
    #
    ;;
esac
echo Done.
echo
