#!/bin/bash
source kernel.txt
mkdir -p ${tmp3v7}
cd ${tmp3v7}

### Download kernel
echo
echo Downloading kernel.
wget -cq --show-progress https://github.com/raspberrypi/linux/archive/rpi-${version}.tar.gz
echo Done.

### Extract
echo
echo Extracting archive.
tar -xf rpi-${version}.tar.gz
#rm -f rpi-${version}.tar.gz #remove
echo Done.

### Setup
cd ${kernel}-${version}
export ARCH=arm
KERNEL=kernel7

### Clean kernel
#make clean
#make mrproper

### Packaging patch
echo
echo Applying packaging patch.
patch -p1 < ../${pat}/rpi3b-v7-packaging.patch &> /dev/null
echo Done.
echo

### Foundation defconfig
case `grep -Fx "foundation_defconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo Making foundation defconfig.
    make ARCH=arm bcm2709_defconfig &> /dev/null
    echo Done.
    ;;
  1)
    #echo
    ;;
  *)
    echo no config found!
    ;;
esac

### Builder defconfig
case `grep -Fx "lessfoundation_defconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo Making builder defconfig.
    cp -f ../${def}/rpi3v7-noinitrd_defconfig arch/arm/configs/
    make ARCH=arm rpi3v7-noinitrd_defconfig &> /dev/null
    echo Done.
    ;;
  1)
    #echo
    ;;
  *)
     echo no config found!
    ;;
esac

### Custom defconfig
case `grep -Fx "custom_defconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo Making ${MYCONFIG}.
    cp -f ../${def}/${MYCONFIG} arch/arm/configs/
    make ARCH=arm ${MYCONFIG} &> /dev/null
    echo Done.
    ;;
  1)
    #echo
    ;;
  *)
    echo no config found!
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo Opening menuconfig.
    sleep 1s
    make menuconfig &> /dev/null
    ;;
  1)
    #echo
    ;;
  *)
    echo grumble! grumble!
    ;;
esac

### Build deb
case `grep -Fx "native=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo --- Building deb packages.
    make -j${cores} ARCH=arm bindeb-pkg
    ;;
  1)
    echo
    echo you are cross compiling
    ;;
  *)
    echo grumble! grumble!
    ;;
esac

case `grep -Fx "crosscompile=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo --- Building deb packages.
    make -j${cores} ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bindeb-pkg
    ;;
  1)
    echo 
    echo you are not cross compiling
    ;;
  *)
    echo grumble! grumble!
    ;;
esac
echo Done.
echo
