#!/bin/bash
source userdata.txt
source lib/ml_func.txt
source lib/source.txt
UD=userdata.txt

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 20 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found."
else 
    userdata
fi

mkdir -p ${TMP4}
cd ${TMP4}

### Download kernel
case `grep -Fx "mainline=1" "../userdata.txt" >/dev/null; echo $?` in
  0)
    download_mainline
    ;;
  1)
    download_stable
    ;;
  *)
    #
    ;;
esac

### Clean kernel
#make clean
#make mrproper

### Patching
patching

### Defconfig
case `grep -Fx "custom_defconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    cconfig
    ;;
  1)
    rpi_config
    ;;
  *)
    #
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    menu_config
    ;;
  *)
    #
    ;;
esac

### Build deb
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    cross_compile
    ;;
  1)
    native_compile
    ;;
  *)
    #
    ;;
esac
echo Done.
echo
