#!/bin/bash
source config.txt

### Download kernel
echo
echo Downloading kernel.
wget -cq https://github.com/raspberrypi/linux/archive/rpi-${version}.tar.gz
echo Done.

### Extract
echo
echo Extracting archive.
tar -xf rpi-${version}.tar.gz
echo Done.
#rm -f rpi-${version}.tar.gz #remove

### Setup
echo
sleep 1s
cd ${kernel}-${version}
export ARCH=arm64

### Clean kernel
#make clean
#make mrproper

### Packaging patch
echo
echo Applying packaging patch.
patch -p1 < ../patches/rpi4b-packaging.patch

### Set defconfig
echo
cp -f ../defconfig/rpi4b_defconfig arch/arm64/configs/
make ARCH=arm64 rpi4b_defconfig

### Foundation defconfig
#make ARCH=arm64 bcm2711_defconfig

### Open menuconfig
#echo
#echo Opening menuconfig.
#sleep 1s
#make menuconfig

### Build deb
echo
echo Building deb packages.
#make -j${cores} ARCH=arm64 bindeb-pkg # native
make -j${cores} ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bindeb-pkg
cd ..

### Move debs
mkdir -p debs
mv -f *.deb debs/
mv -f *.buildinfo debs/
mv -f *.changes debs/
echo
echo Done.
