#!/bin/bash
source kernel.txt
mkdir -p ${tmp4}
cd ${tmp4}

### Download kernel
echo
echo Downloading kernel.
wget -cq --show-progress https://github.com/raspberrypi/linux/archive/rpi-${version}.tar.gz
echo Done.

### Extract
echo
echo Extracting archive.
tar -xf rpi-${version}.tar.gz
#rm -f rpi-${version}.tar.gz #remove
echo Done.

### Setup
cd ${kernel}-${version}
export ARCH=arm64

### Clean kernel
#make clean
#make mrproper

### Packaging patch
echo
echo Applying packaging patch.
patch -p1 < ../${pat}/rpi4b-packaging.patch

### Foundation defconfig
case `grep -Fx "foundation_defconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
   make ARCH=arm64 bcm2711_defconfig
    ;;
  1)
    echo *You don't like the Foundation?
    ;;
  *)
    echo no config found!
    ;;
esac

### Builder defconfig
case `grep -Fx "rpiimgbuilder_defconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
   cp -f ../${def}/rpi4b_defconfig arch/arm64/configs/
   make ARCH=arm64 rpi4b_defconfig
    ;;
  1)
    echo *Rpiimgbuilder: I guess you prefer initrd?
    ;;
  *)
    echo no config found!
    ;;
esac

### Custom defconfig
case `grep -Fx "custom_defconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
   cp -f ../${def}/custom_defconfig arch/arm64/configs/
   make ARCH=arm64 custom_defconfig
    ;;
  1)
    echo *Custom: It can be risky business!
    ;;
  *)
    echo no config found!
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=0" "../../kernel.txt" >/dev/null; echo $?` in
  0)
   echo
   echo Opening menuconfig.
   sleep 1s
   make menuconfig
    ;;
  1)
    echo menuconfig set to false
    ;;
  *)
    echo grumble! grumble!
    ;;
esac

### Build deb
echo
echo Building deb packages.
#make -j${cores} ARCH=arm64 bindeb-pkg # native
make -j${cores} ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bindeb-pkg
echo Done.
echo
