#!/bin/bash
source config.txt

### Download kernel
echo
echo Downloading kernel.
wget -cq --show-progress https://github.com/raspberrypi/linux/archive/rpi-${version}.tar.gz
echo Done.

### Extract
echo
echo Extracting archive.
tar -xf rpi-${version}.tar.gz
echo Done.
#rm -f rpi-${version}.tar.gz #remove

### Setup
echo
sleep 1s
cd ${kernel}-${version}
export ARCH=arm
KERNEL=kernel7l

### Clean kernel
#make clean
#make mrproper

### Packaging patch
echo
echo Applying packaging patch.
patch -p1 < ../patches/rpi4b-v7-packaging.patch

### Set defconfig
echo
cp -f ../defconfig/rpi4b-v7_defconfig arch/arm/configs/
make ARCH=arm rpi4b-v7_defconfig

### Foundation defconfig
#make ARCH=arm bcm2711_defconfig

### Open menuconfig
#echo
#echo Opening menuconfig.
#sleep 1s
#make menuconfig

### Build deb
echo
echo Building deb packages.
make -j4 ARCH=arm bindeb-pkg # native
#make -j4 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bindeb-pkg
cd ..

### Move debs
mkdir -p debs
mv -f *.deb debs/
mv -f *.buildinfo debs/
mv -f *.changes debs/
echo
echo Done.
