#!/bin/bash
# ROOTFS TARBALLS
RED="\e[0;31m"
BRED="\e[1;31m"
GRN="\e[0;32m"
YLW="\e[1;33m"
GRY="\e[0;37m"
WHT="\e[1;37m"
FIN="\e[0m"
source board.txt > /dev/null 2>&1
source userdata.txt > /dev/null 2>&1
source lib/source
source lib/function/rootfs
UD=userdata.txt

userdata(){
echo ""
echo -e "Please create a ${WHT}userdata.txt${FIN} file"
while [ true ]; do
read -t 10 -n 1
if [ $? = 0 ]; then
	exit;
else
	echo -e "run make config";
fi
done
}

if [ -f "$UD" ]; then
	:;
else
	userdata;
fi
validation
if [[ "$ROOTFS_ARCH" == "rootfs-armel" ]]; then
	if [[ "$DISTRO" == "ubuntu" ]]; then
		echo -e "${YLW}Ubuntu is not supported${FIN}.";
		echo "";
		exit;
	fi
fi
if [ $verbose -eq 1 ]; then
	set -eux -o pipefail;
else
	set -eu -o pipefail;
fi
if [[ "$DISTRO" == "devuan" ]]; then
	devuan_keyring;
fi
if [[ `grep -w "Ubuntu" "/etc/os-release"` ]]; then
	:;
else
	if [[ "$DISTRO" == "ubuntu" ]]; then
		ubuntu_setup;
	fi
fi
ROOT="sysroot"
RELEASE=${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
if [ -e $RELEASE ]; then
	ls $RELEASE
	exit;
fi
echo ""
echo -e "${WHT}Starting debootstrap${FIN} ..."
# start debootstrap
mkdir -p ${ROOT}/usr/bin
cp $(command -v "${STATIC}") ${ROOT}/usr/bin;
if [[ "$DISTRO" == "devuan" ]]; then
	devuan_debootstrap;
else
	run_debootstrap;
fi
if [ -e ${ROOT}/usr/bin/${STATIC} ]; then
	rm -f ${ROOT}/usr/bin/${STATIC}
fi
rm -f ${ROOT}/var/cache/debconf/*

# finish
echo
echo -e "${WHT}Archiving root filesystem${FIN} ..."
cd ${ROOT}
echo -en ${WHT}
XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$RELEASE)
echo -en ${FIN}
cd ..

rm -fdr ${ROOT}
if [ -e /usr/share/debootstrap/scripts/chimaera ]; then
	rm -f /usr/share/debootstrap/scripts/chimaera;
fi
if [ -e /usr/share/debootstrap/scripts/daedalus ]; then
	rm -f /usr/share/debootstrap/scripts/daedalus;
fi
clear -x
