#!/bin/bash
#ARMEL ROOTFS
RED="\e[0;31m"
BRED="\e[1;31m"
GRN="\e[0;32m"
YLW="\e[1;33m"
GRY="\e[0;37m"
WHT="\e[1;37m"
FIN="\e[0m"
source userdata.txt > /dev/null 2>&1;
source lib/source
source lib/function/rootfs
UD=userdata.txt

userdata(){
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    :;
else 
    userdata
fi
if `grep -Fx 'DISTRO="ubuntu"' "userdata.txt" >/dev/null;`
	then echo -e "${YLW}Ubuntu is not supported${FIN}." && exit;
fi
if `grep -Fx 'DISTRO="devuan"' "userdata.txt" >/dev/null;`
	then check_keyring;
fi
echo
validation
if `grep -Fx "verbose=1" "userdata.txt" > /dev/null 2>&1;`
	then set -eux -o pipefail;
	else set -eu -o pipefail;
fi
ROOT="sysroot"
ROOTFS_ARCH="rootfs-armel"
RELEASE=${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
URL="https://github.com/pyavitz/rootfs-tarballs/releases/download/rootfs/"
DOWNLOAD="aria2c -c --download-result=hide --console-log-level=error --disable-ipv6=true --summary-interval=0 --show-files=false"
docker_check(){
if grep "docker" /proc/1/cgroup > /dev/null 2>&1;
	then echo -e "Docker detected ..." && ${DOWNLOAD} ${URL}$RELEASE && echo -e " Done." && exit;
fi
}
find_rootfs(){
if [[ `wget -S --spider ${URL}$RELEASE 2>&1 | grep 'HTTP/1.1 200 OK'` ]];
	then docker_check; else echo -e "Are you kidding me? Check the userdata file." && exit;
fi
}
if ls $RELEASE > /dev/null 2>&1;
	then ls $RELEASE && exit;
fi
find_rootfs
echo -e "${GRN}Starting debootstrap${FIN} ..."
echo -e -n ${RED}

# start debootstrap
mkdir -p ${ROOT}/usr/bin
cp $(which "qemu-arm-static") ${ROOT}/usr/bin
if `grep -Fx 'DISTRO="devuan"' "userdata.txt" >/dev/null;`
	then armv6_devuan;
	else armv6_debootstrap
fi
rm -f ${ROOT}/usr/bin/qemu-arm-static
rm -f ${ROOT}/var/cache/debconf/*

# finish
echo
echo -e "${BRED}Archiving root filesystem${FIN} ..."
cd ${ROOT}
echo -e -n ${WHT}
XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$RELEASE)
echo -e -n ${FIN}
cd ..

rm -fdr ${ROOT}
clear
