#!/bin/bash
#ARMEL ROOTFS
RED="\e[0;31m"
BRED="\e[1;31m"
GRN="\e[0;32m"
YLW="\e[1;33m"
GRY="\e[0;37m"
WHT="\e[1;37m"
FIN="\e[0m"
source userdata.txt > /dev/null 2>&1;
source lib/source
source lib/function/rootfs
UD=userdata.txt

userdata(){
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    :;
else 
    userdata
fi
if `grep -Fx "ubuntu=1" "userdata.txt" > /dev/null 2>&1;`
	then echo -e "${YLW}Ubuntu is not supported${FIN}." && exit;
fi
check_keyring
validation
if `grep -Fx "verbose=1" "userdata.txt" > /dev/null 2>&1;`
	then set -eux -o pipefail;
	else set -eu -o pipefail;
fi
RAM=0
PROXY=""
IMAGE_FOLDER="img/"
ROOTFS_ARCH="rootfs-armel"
DEBIAN=debian-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
DEVUAN=devuan-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
if ls $DEBIAN > /dev/null 2>&1;
	then ls $DEBIAN && exit;
fi
if ls $DEVUAN > /dev/null 2>&1;
	then ls $DEVUAN && exit;
fi
echo -e "${GRN}Starting debootstrap${FIN} ..."
echo -e -n ${RED}
IMAGE_FILE_SUFFIX="$(date +%F)"
if `grep -Fx "debian=1" "userdata.txt" > /dev/null 2>&1;`
	then IMAGE_FILE_NAME="debian-${DISTRO_VERSION}-${ROOTFS_ARCH}.img";
fi
if `grep -Fx "devuan=1" "userdata.txt" > /dev/null 2>&1;`
	then IMAGE_FILE_NAME="devuan-${DISTRO_VERSION}-${ROOTFS_ARCH}.img";
fi
if [ $RAM -ne 0 ]; then
	IMAGE_FOLDER="ram/"
fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then
	mount -t tmpfs -o size=1G tmpfs $IMAGE_FOLDER
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partition;
	else partition > /dev/null 2>&1;
fi
mkdir -p p1/etc/apt/apt.conf.d p1/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"
mkdir -p p1/usr/bin
cp $(which "qemu-arm-static") p1/usr/bin
if `grep -Fx "debian=1" "userdata.txt" > /dev/null 2>&1;`
	then debian_armv6;
fi
if `grep -Fx "devuan=1" "userdata.txt" > /dev/null 2>&1;`
	then devuan_armv6;
fi
if [ -n "$PROXY" ] ; then
	tee "p1/etc/apt/apt.conf.d/30proxy" <<EOF
Acquire::http::proxy "http://127.0.0.1:3142";
EOF
fi

rm p1/usr/bin/qemu-arm-static

if [ -n "$PROXY" ] ; then
	rm p1/etc/apt/apt.conf.d/30proxy
fi
rm p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io

### Finish
echo
echo -e -n ${FIN}
echo -e -n ${GRY}
e4defrag -c p1
echo -e -n ${FIN}
echo
echo -e "${BRED}Archiving root filesystem${FIN} ..."
cd p1
echo -e -n ${WHT}
if `grep -Fx "debian=1" "../userdata.txt" > /dev/null 2>&1;`
	then XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$DEBIAN);
fi
if `grep -Fx "devuan=1" "../userdata.txt" > /dev/null 2>&1;`
	then XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$DEVUAN);
fi
echo -e -n ${FIN}
cd ..

umount p1

losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then
	umount "${IMAGE_FOLDER}"
fi
rmdir "${IMAGE_FOLDER}"
rmdir p1
rm -f debian-${DISTRO_VERSION}-${ROOTFS_ARCH}.img > /dev/null 2>&1
rm -f devuan-${DISTRO_VERSION}-${ROOTFS_ARCH}.img > /dev/null 2>&1
clear
