#!/bin/bash
#AARCH64 ROOTFS
RED="\e[0;31m"
BRED="\e[1;31m"
GRN="\e[0;32m"
YLW="\e[1;33m"
GRY="\e[0;37m"
WHT="\e[1;37m"
FIN="\e[0m"
source userdata.txt > /dev/null 2>&1;
source lib/source
source lib/function/rootfs
UD=userdata.txt

userdata(){
echo ""
echo -e "Please create a ${WHT}userdata.txt${FIN} file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo -e "run make config"
fi
done
}

if [ -f "$UD" ]; then
    :;
else 
    userdata
fi
validation
if [[ `grep -w 'DISTRO="devuan"' "userdata.txt"` ]]; then
	devuan_keyring;
fi
if [[ `grep -w "Ubuntu" "/etc/os-release"` ]]; then
	:;
else
	if [[ `grep -w 'DISTRO="ubuntu"' "userdata.txt"` ]]; then
		ubuntu_keyring;
	fi
fi
if [[ `grep -w "verbose=1" "userdata.txt"` ]]; then
	set -eux -o pipefail;
else
	set -eu -o pipefail;
fi
ROOT="sysroot"
ROOTFS_ARCH="rootfs-aarch64"
RELEASE=${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
if [ -e $RELEASE ]; then
	ls $RELEASE
	exit;
fi
echo -e "${WHT}Starting debootstrap${FIN} ..."
echo -e -n ${GRN}

# start debootstrap
mkdir -p ${ROOT}/usr/bin
cp $(command -v "qemu-aarch64-static") ${ROOT}/usr/bin
if [[ `grep -w 'DISTRO="devuan"' "userdata.txt"` ]]; then
	arm64_devuan;
else
	arm64_debootstrap;
fi
rm -f ${ROOT}/usr/bin/qemu-aarch64-static
rm -f ${ROOT}/var/cache/debconf/*

# finish
echo
echo -e "${BRED}Archiving root filesystem${FIN} ..."
cd ${ROOT}
echo -e -n ${WHT}
XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$RELEASE)
echo -e -n ${FIN}
cd ..

rm -fdr ${ROOT}
if [ -e /usr/share/debootstrap/scripts/chimaera ]; then
	rm -f /usr/share/debootstrap/scripts/chimaera;
fi
clear
