#!/bin/bash
source lib/function/echoes
source lib/source
validation
source board.txt
source userdata.txt
source lib/function/compiler
source lib/function/rpi-commit
source lib/function/wireless
source lib/function/modconfig

# prep
validation
if [ $verbose -eq 1 ]; then
	set -x;
fi
compiler
source_dir
# commit
echo
echo -e -n "${WHT}Paste commit: ${FIN}"
read commit

if [ -e ${CKERNEL}-$commit ]; then
	echo "";
	echo -en "${WHT}${CKERNEL}-$commit${FIN}";
	echo -en " ${PNK}[${FIN}${YLW}removing${FIN}${PNK}]${FIN} ";
	rm -fdr ${CKERNEL}-$commit;
	echo -en "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}";
fi

### Download kernel
if [[ `wget -S --spider https://github.com/raspberrypi/linux/archive/$commit.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	download;
else
	echo ""
	echo -e "${WHT}It appears the commit you selected is not available${FIN}?"
	exit > /dev/null 2>&1;
fi

# Extract
extract

# Setup
setup
firmware

# Packaging
packaging

# Defconfig
if [ $custom_defconfig -eq 1 ]; then
	cconfig;
else
	fconfig;
fi

# Menuconfig
if [ $menuconfig -eq 1 ]; then
	menuconfig;
fi

# Builddeb
if [ $crosscompile -eq 1 ]; then
	ccompile;
else
	ncompile;
fi

# Finish
echo ""
cd ..
rm -f {linux-libc-dev*.deb,*.buildinfo,*.changes}
if [[ `ls ../${OUTPUT}/*.deb` ]] > /dev/null 2>&1; then
	mkdir -p ../${OUTPUT}/tmp;
	mv -f ../${OUTPUT}/*.deb ../${OUTPUT}/tmp;
fi
mkdir -p ../${OUTPUT}
mv -f *.deb ../${OUTPUT}/
echo_done
exit 0
