#!/bin/bash
source board.txt > /dev/null 2>&1
source userdata.txt > /dev/null 2>&1
source lib/source
source lib/function/echoes
source lib/function/compiler
source lib/function/rpi-linux
source lib/function/wireless
source lib/function/modules
UD=userdata.txt

userdata(){
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ]; do
read -t 3 -n 1
if [ $? = 0 ]; then
	exit;
else
	dialog --infobox "Please review the README.md or run make config." 3 51;
fi
done
}

if [ -f "$UD" ]; then
	:;
else
	userdata;
fi

# prep
validation
if [ $verbose -eq 1 ]; then
	set -x;
fi
compiler
source_dir
clean_source

# Download kernel
if [[ `wget -S --spider https://raw.githubusercontent.com/raspberrypi/linux/rpi-${VERSION}/Makefile 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	download;
else
	echo ""
	echo -e "${WHT}It appears the branch you selected is not available${FIN}?"
	exit > /dev/null 2>&1;
fi

# Extract
extract

# Setup
setup
if [[ "$BOARD_EXT" == "rpi-4" ]]; then
	rpi4_firmware;
else
	rpi_firmware;
fi

# Patching
patching

# Defconfig
if [ $custom_defconfig -eq 1 ]; then
	cconfig;
else
	fconfig;
fi

# Menuconfig
if [ $menuconfig -eq 1 ]; then
	menuconfig;
fi

# Builddeb
if [ $crosscompile -eq 1 ]; then
	ccompile;
else
	ncompile;
fi

# Finish
echo ""
cd ..
rm -f {linux-libc-dev*.deb,*.buildinfo,*.changes}
if [[ `ls ../${OUTPUT}/*.deb` ]] > /dev/null 2>&1; then
	mkdir -p ../${OUTPUT}/tmp;
	mv -f ../${OUTPUT}/*.deb ../${OUTPUT}/tmp/;
fi
mkdir -p ../${OUTPUT}
mv -f *.deb ../${OUTPUT}/
echo_done
