#!/bin/bash
source userdata.txt > /dev/null 2>&1;
source lib/function/echoes
source lib/source
UD=userdata.txt

userdata(){
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please review the README.md." 3 33
fi
done
}

if [ -f "$UD" ]; then :
else 
    userdata
fi

if [[ `grep -w "rpiuser=1" "userdata.txt"` ]]; then
	make kernel;
else
	if [[ `grep -w "admin=1" "userdata.txt"` ]]; then
		make kernel;
	else
		if [[ `grep -w "devuser=1" "userdata.txt"` ]]; then
			make mainline;
		else
			echo "${WHT}Something went wrong? Please check the userdata.txt file.${FIN}"
			exit;
		fi
	fi
fi
