#!/bin/bash
source userdata.txt > /dev/null 2>&1;
source lib/function/echoes
source lib/source
UD=userdata.txt

userdata(){
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please review the README.md." 3 33
fi
done
}

if [ -f "$UD" ]; then :
else 
    userdata
fi

if `grep -Fx "rpiuser=1" "userdata.txt" >/dev/null;`
	then make kernel;
fi
if `grep -Fx "admin=1" "userdata.txt" >/dev/null;`
	then make kernel;
fi
if `grep -Fx "devuser=1" "userdata.txt" >/dev/null;`
	then make mainline;
fi
