#!/usr/bin/env bash
if [ -f /root/services.txt ]; then
	source /root/services.txt;
fi
source /root/universal.txt
source /root/source.txt
source /root/board.txt > /dev/null 2>&1
source /root/userdata.txt > /dev/null 2>&1
if [ $verbose -eq 1 ]; then
	set -x;
fi
source /root/${DISTRO}.txt
UNMINIMIZE=/usr/local/sbin/unminimize
URL="https://raw.githubusercontent.com/pyavitz/scripts/master/"

set -o errexit
set -o pipefail
set -o nounset

echo "nameserver ${NAMESERVER1}" > /etc/resolv.conf
echo "nameserver ${NAMESERVER2}" >> /etc/resolv.conf

mount -t proc proc proc/
mount -t sysfs sys sys/

export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y apt-utils

# Locales
set_locales

# Timezone
set_timezone

apt upgrade -y
apt dist-upgrade -y
apt autoremove -y
if [[ "$DISTRO" == "ubuntu" ]]; then
	if [ -f "$UNMINIMIZE" ]; then
		echo 'y' | unminimize;
	fi
	apt_preferences;
	echo "";
fi
if [ $ext4 -eq 1 ]; then
	apt install -y e2fsprogs;
fi
if [ $btrfs -eq 1 ]; then
	apt install -y btrfs-progs;
fi
if [ $xfs -eq 1 ]; then
	apt install -y xfsprogs;
fi
if [[ "$DISTRO" == "debian" ]]; then
	apt install -y ${PKG1} ${SYSMODS} ${FIRMWARE} resolvconf openssh-client openssh-server;
fi
if [[ "$DISTRO" == "devuan" ]]; then
	apt install -y openssh-client openssh-server --no-install-recommends;
	apt install -y ${PKG1} ${SYSMODS} ${FIRMWARE} openresolv ifupdown-extra;
fi
if [[ "$DISTRO" == "ubuntu" ]]; then
	apt install -y ${PKG1} ${SYSMODS} openresolv network-manager openssh-client openssh-server;
fi
# apt clean
apt -y clean
apt -y autoclean

# User options
echo -n "${BOARD}" > /etc/hostname;
sed -i "1 a 127.0.1.1	${BOARD}" /etc/hosts;
if [ $useracct -eq 0 ]; then
	echo "";
	adduser ${USERNAME} --gecos ${NAME} --disabled-password
	echo "${USERNAME}:${PASSWORD}" | chpasswd
	adduser ${USERNAME} sudo
	adduser ${USERNAME} audio
	adduser ${USERNAME} dialout
	adduser ${USERNAME} video
	adduser ${USERNAME} disk
	adduser ${USERNAME} plugdev
	adduser ${USERNAME} netdev
	adduser ${USERNAME} bluetooth
	adduser ${USERNAME} input
	adduser ${USERNAME} tty
	adduser ${USERNAME} i2c
	groupadd gpio
	groupadd spi
	adduser ${USERNAME} gpio
	adduser ${USERNAME} spi
fi
if [ $useracct -eq 1 ]; then
	mkdir -p /boot;
	mkdir -p /usr/local/sbin;
	mv -f /root/useracct/useraccount /usr/local/sbin/;
	chmod +x /usr/local/sbin/useraccount;
	mv -f /root/{nanorc-user,user-ini} /etc/opt/;
	mv -f /root/useracct/useraccount.txt /boot/rename_to_useraccount.txt;
	if [[ "$DISTRO" == "devuan" ]]; then
		mkdir -p /etc/init.d;
		mv -f /root/useracct/useraccount.init /etc/init.d/useraccount;
		chmod +x /etc/init.d/useraccount;
		update-rc.d useraccount defaults 5;
		rm -fdr /root/useracct;
	else
		mkdir -p /etc/systemd/system/;
		mv -f /root/useracct/useraccount.service /etc/systemd/system/;
		systemctl enable useraccount > /dev/null 2>&1;
		rm -fdr /root/useracct;
	fi
fi
if [ $rootpasswd -eq 1 ]; then
	root_password;
fi

# Sudoers file
if [ $useracct -eq 0 ]; then
	echo "";
	tee /etc/sudoers.d/010_${USERNAME}-nopasswd <<EOF
${USERNAME} ALL=(ALL) NOPASSWD: ALL
EOF
fi

# User script (function 2)
if [ $uscripts -eq 1 ]; then
	echo ""
	uscripts_stage2;
fi

# Skins
cd ~
mkdir -p /usr/share/mc/skins
mv -f darkgreen.ini /usr/share/mc/skins/darkgreen.ini
mv -f darkred.ini /usr/share/mc/skins/darkred.ini
mkdir -p /root/.config/mc
mv -f root-ini /root/.config/mc/ini
mv -f nanorc-root /root/.nanorc
chown -R root:root /root
if [ $useracct -eq 0 ]; then
	mkdir -p /home/${USERNAME}/.config/mc;
	mv -f user-ini /home/${USERNAME}/.config/mc/ini;
	mv -f nanorc-user /home/${USERNAME}/.nanorc;
	chown -R ${USERNAME}:${USERNAME} /home/${USERNAME};
fi

# Scripts
echo ""
echo "Moving scripts ..."
sleep 1s
cd ~
mkdir -p /usr/local/bin
mkdir -p /usr/local/sbin
if [[ "$BOARD_EXT" == "rpi-4" ]]; then
	wget -cq --show-progress ${URL}write2usb;
	wget -cq --show-progress ${URL}deb-eeprom;
	mv -f {write2usb,deb-eeprom} /usr/local/bin/;
fi
wget -cq --show-progress ${URL}swh
wget -cq --show-progress ${URL}fetch
wget -cq --show-progress ${URL}governor
mv -f {swh,fetch,governor,setup,sysinfo,smon} /usr/local/bin/
initrd_script
mv -f credentials.sh /usr/local/bin/credentials
mv -f firstboot.sh /usr/local/sbin/firstboot
if [[ "$DISTRO" == "devuan" ]]; then
	# Inits
	mv -f firstboot.init /etc/init.d/firstboot;
	mv -f leds.init /etc/init.d/leds;
	mv -f governor.init /etc/init.d/governor;
	mv -f bthelper /etc/init.d/;
	mv -f zramswap /etc/init.d/;
	mv -f network /etc/init.d/;
	mv -f credentials /etc/init.d/;
fi
mv -f growpart /usr/bin/
chmod +x /usr/bin/growpart
chown root:root /usr/bin/growpart
chmod +x /usr/local/bin/*
chmod +x /usr/local/sbin/*
chown -R root:root /usr/local/bin/
chown -R root:root /usr/local/sbin/
echo "Done."

# MOTD
echo ""
echo "Adding motd ..."
sleep 1s
mkdir -p /etc/update-motd.d
tee /etc/update-motd.d/15-brand <<EOF
#!/bin/bash
echo
toilet -f small --filter metal '${MOTD}'
echo 
EOF
mv -f 20-sysinfo /etc/update-motd.d/20-sysinfo
if [ -e /etc/update-motd.d/10-help-text ]; then
	rm -f /etc/update-motd.d/10-help-text;
fi
chmod +x /etc/update-motd.d/*
chown root:root /etc/update-motd.d/15-brand
chown root:root /etc/update-motd.d/20-sysinfo
echo "Done."

# Extra firmware
extra_firmware

# Udev rule
if [ -e /root/99-com.rules ]; then
	cd ~
	mkdir -p /lib/udev/rules.d/;
	mv -f 99-com.rules /lib/udev/rules.d/;
fi

# Network Setup
if [[ "$DISTRO" == "ubuntu" ]]; then
	network_manager;
else
	network_setup > /dev/null 2>&1;
fi

# ZSWAP
zramswap_config

# MOTD instructions
rm -f /etc/motd
echo "" > /etc/motd
echo "To set Locales, Timezone, Keyboard and Audio. Execute: setup -r" >> /etc/motd
echo "" >> /etc/motd
chown root:root /etc/motd

# Wireless regdb
wireless_regdb

# Adding sys-mods
raspberrypi_sys_mods
if [ -f /etc/sudoers.d/010_pi-nopasswd ]; then
	rm -f /etc/sudoers.d/010_pi-nopasswd;
fi

# Pi Bluetooth
echo ""
echo "Installing pi-bluetooth ..."
sleep 1s
if [[ "$DISTRO" == "ubuntu" ]]; then
	git clone https://github.com/pyavitz/pi-bluetooth.git -b ubuntu;
else
	git clone https://github.com/pyavitz/pi-bluetooth.git;
fi
cd pi-bluetooth
chmod +x debian/rules
dpkg-buildpackage -us -uc
cd ~
dpkg -i pi-bluetooth_*.deb
rm -fdR pi-bluetooth*
echo "Done."

#  Raspi userland
rpi_userland

# Adding eeprom
if [[ "$BOARD_EXT" == "rpi-4" ]]; then
	bcm2711_eeprom;
fi

# Remove zstd compression (not supported by older kernels)
if [[ "$DISTRO" == "ubuntu" ]] && [[ "$DISTRO_VERSION" == "jammy" ]]; then
	if [[ `grep -w "COMPRESS=zstd" "/etc/initramfs-tools/initramfs.conf"` ]]; then
		sed -i 's/COMPRESS=zstd/COMPRESS=xz/g' /etc/initramfs-tools/initramfs.conf;
	fi
fi

# Kernel
stage2_kernel

# Modules
if [[ "$BOARD_EXT" == "rpi-4" ]]; then
	bcm_modules > /dev/null 2>&1;
fi
if [[ "$BOARD" == "bcm2710" ]]; then
	bcm2710_modules > /dev/null 2>&1;
fi
if [[ "$BOARD" == "bcm2709" ]]; then
	bcm2710_modules > /dev/null 2>&1;
fi
if [[ "$BOARD" == "bcm2708" ]]; then
	bcm_modules > /dev/null 2>&1;
fi

# Clean misc files
rm -f {*.patch,*led*,*eeprom*}

# RPi Hack
if [[ "$BOARD" == "bcm2708" ]]; then
	ln -s /lib/ld-linux.so.3 /lib/ld-linux-armhf.so.3;
fi

# Flush runtime journal
if [[ "$BOARD" == "bcm2708" ]]; then
	:;
else
	systemd_journald;
fi

# Vchiq permissions
echo 'SUBSYSTEM=="vchiq",GROUP="video",MODE="0660"' > /etc/udev/rules.d/10-vchiq-permissions.rules
echo 'SUBSYSTEM=="vcio",GROUP="video",MODE="0660"' >> /etc/udev/rules.d/10-vchiq-permissions.rules
echo 'SUBSYSTEM=="vc-mem",GROUP="video",MODE="0660"' >> /etc/udev/rules.d/10-vchiq-permissions.rules

if [[ "$DISTRO" == "devuan" ]]; then
	if [ $btrfs -eq 1 ]; then
		btrfs_udev-rule;
	fi
fi

echo ""
echo "Checking Services ..."
sleep 1s
if [[ "$DISTRO" == "devuan" ]]; then
	echo "== Sysvinit";
	led_script > /dev/null 2>&1;
	enable_services > /dev/null 2>&1;
else
	echo "== Systemd";
	firstboot_service > /dev/null 2>&1;
	credentials_service > /dev/null 2>&1;
	governor_service > /dev/null 2>&1;
	led_script > /dev/null 2>&1;
	led_service > /dev/null 2>&1;
	rc-local_service > /dev/null 2>&1;
	enable_services > /dev/null 2>&1;
fi
echo "Done."

# Finish
echo ""
echo "Finalizing ..."
echo ""
sleep 1s

umount /proc /sys
