#!/bin/bash
source lib/ubuntu_func.txt
source lib/source.txt
source userdata.txt
UD=userdata.txt

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 20 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found."
else 
    userdata
fi

set -x
RAM=0
PROXY=""
IMAGE_FOLDER="img/"
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then DEVICE_SOC="bcm2711" ;
fi 
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then DEVICE_SOC="bcm2710" ;
fi
set -eux -o pipefail
IMAGE_DATE="$(date +%F)"
IMAGE_FILE_NAME="${DEVICE_SOC}-ubuntu-${DISTRO_VERSION}-${IMAGE_DATE}.img"
if [ $RAM -ne 0 ]; then
	IMAGE_FOLDER="ram/"
fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then
	mount -t tmpfs -o size=3G tmpfs $IMAGE_FOLDER
fi
truncate -s ${UBUNTUIMGSIZE} "${IMAGE_FOLDER}${IMAGE_FILE_NAME}"
fdisk "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" <<EOF
o
n
p
1
2048
524287
a
c
t
b
n
p
2
524288

p
w

EOF
IMAGE_LOOP_DEV="$(losetup --show -f ${IMAGE_FOLDER}${IMAGE_FILE_NAME})"
IMAGE_LOOP_DEV_BOOT="${IMAGE_LOOP_DEV}p1"
IMAGE_LOOP_DEV_ROOTFS="${IMAGE_LOOP_DEV}p2"
partprobe "${IMAGE_LOOP_DEV}"
mkfs.vfat -n BOOT "${IMAGE_LOOP_DEV_BOOT}"
mkfs.ext4 -L ROOTFS "${IMAGE_LOOP_DEV_ROOTFS}"
mkdir -p p1 p2
mount "${IMAGE_LOOP_DEV_BOOT}" p1
mount "${IMAGE_LOOP_DEV_ROOTFS}" p2
sync
umount p2
mount -o defaults,noatime "${IMAGE_LOOP_DEV_ROOTFS}" p2

### partition uuid
partition_uuid

### cmd line
cmdline

### config dot txt
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then bcm2711_config ;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then bcm2710_config ;
fi
### Fetching boot bits
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then rpi4_bootbins ;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then rpi_bootbins ;
fi
### cleaning boot bits
rm -f firmware/boot/*

### rootfs
aarch64_rootfs

mkdir -p p2/etc/apt/apt.conf.d p2/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "p2/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"

mkdir -p p2/usr/bin
cp $(which "qemu-aarch64-static") p2/usr/bin

tee p2/etc/fstab <<EOF
UUID=${BOOT_UUID}	/boot		vfat    defaults 0 2
UUID=${ROOT_UUID}	/		ext4	defaults,noatime,nodiratime,commit=600,errors=remount-ro 0 1
tmpfs	/tmp		tmpfs	defaults,nosuid 0 0
EOF

if [ -n "$PROXY" ] ; then
	tee "p2/etc/apt/apt.conf.d/30proxy" <<EOF
Acquire::http::proxy "http://127.0.0.1:3142";
EOF
fi

# setup stage2
cp scripts/ubuntu-stage2 p2/root
cp lib/ubuntu_func.txt p2/root
cp lib/source.txt p2/root
cp userdata.txt p2/root
cp soc.txt p2/root
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
	then cp ${TMP4}/*.deb p2/root ;
fi
if `grep -Fx "bcm2710" "soc.txt" >/dev/null;`
	then cp ${TMP3}/*.deb p2/root ;
fi
cp files/ubuntu/misc/* p2/root
cp files/ubuntu/patches/* p2/root
cp files/ubuntu/rules/* p2/root
cp files/ubuntu/scripts/* p2/root
cp files/misc/* p2/root
cp files/scripts/* p2/root
cp files/users/* p2/root
if ls firmware/firmware-nonfree-master.tar.gz > /dev/null 2>&1;
	then cp firmware/firmware-nonfree-master.tar.gz p2/root > /dev/null 2>&1;
	else rpi-firmware && cp firmware/firmware-nonfree-master.tar.gz p2/root;
fi
cp firmware/fw-0a5c_21e8.hcd p2/root
# Mount and chroot
mount -o bind p1 p2/boot
mount -o bind /dev p2/dev
mount -o bind /dev/pts p2/dev/pts
chroot p2 /root/ubuntu-stage2
# unmount
umount p2/dev/pts
umount p2/dev
umount p2/boot

rm p2/usr/bin/qemu-aarch64-static
rm p2/root/ubuntu-stage2
rm p2/root/ubuntu_func.txt
rm p2/root/source.txt
rm p2/root/userdata.txt
rm p2/root/soc.txt
rm -f p2/var/cache/debconf/*

if [ -n "$PROXY" ] ; then
	rm p2/etc/apt/apt.conf.d/30proxy
fi
rm p2/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io

### Finish
e4defrag -c p2

umount p2
umount p1

losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then
	umount "${IMAGE_FOLDER}"
fi
rmdir "${IMAGE_FOLDER}"
rmdir p1 p2
rm -f part-uuid.txt soc.txt
