#!/usr/bin/env bash
source /root/ubuntu.txt
source /root/universal.txt
source /root/source.txt
source /root/userdata.txt
UNMINIMIZE=/usr/local/sbin/unminimize
URL="https://raw.githubusercontent.com/pyavitz/scripts/master/"

set -o errexit
set -o pipefail
set -o nounset

echo 'nameserver 8.8.8.8' > /etc/resolv.conf
echo 'nameserver 8.8.4.4' >> /etc/resolv.conf

mount -t proc proc proc/
mount -t sysfs sys sys/

export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y apt-utils

### Locales
set_locales

### Timezone
set_timezone

apt upgrade -y
apt dist-upgrade -y

if [ -f "$UNMINIMIZE" ]; then
    echo 'y' | unminimize
else 
    echo "$UNMINIMIZE does not exist."
fi

apt_preferences
echo
if [[ `grep -w "ext4=1" "/root/userdata.txt"` ]]; then
	apt install -y e2fsprogs;
else
	if [[ `grep -w "btrfs=1" "/root/userdata.txt"` ]]; then
		apt install -y btrfs-progs;
	else
		if [[ `grep -w "xfs=1" "/root/userdata.txt"` ]]; then
			apt install -y xfsprogs;
		fi
	fi
fi
apt install -y ${UBUNTU1} ${UBUNTU2}
apt -y clean
apt -y autoclean

#### Scripts
echo
echo Moving scripts.
sleep 1s
cd ~
mkdir -p /usr/local/bin
mkdir -p /usr/local/sbin
# Scripts
led_service
if [[ `grep -w "bcm2711" "/root/soc.txt"` ]]; then
	wget -cq --show-progress ${URL}write2usb
	wget -cq --show-progress ${URL}deb-eeprom
	mv -f {write2usb,deb-eeprom} /usr/local/bin/;
fi
mv -f growpart /usr/bin/
wget -cq --show-progress ${URL}fetch
wget -cq --show-progress ${URL}governor
mv -f {run-setup,sysinfo,smon,credentials,fetch,governor} /usr/local/bin/
if [[ `grep -w "userscripts=1" "/root/userdata.txt"` ]]; then
	uscripts_stage2;
fi
initrd_script
# Service
mv -f firstboot.sh /usr/local/sbin/firstboot
chmod +x /usr/bin/growpart
chown root:root /usr/bin/growpart
chmod +x /usr/local/bin/*
chmod +x /usr/local/sbin/*
chown -R root:root /usr/local/bin/
chown -R root:root /usr/local/sbin/
echo Done.

#### MOTD
echo
echo Adding motd.
sleep 1s
mkdir -p /etc/update-motd.d
tee /etc/update-motd.d/15-brand <<EOF
#!/bin/bash
echo
toilet -f small --filter metal '${BRAND}'
echo 
EOF
mv -f 20-sysinfo /etc/update-motd.d/20-sysinfo
rm -f /etc/update-motd.d/10-help-text
chmod +x /etc/update-motd.d/*
chown root:root /etc/update-motd.d/15-brand
chown root:root /etc/update-motd.d/20-sysinfo
echo Done.

####
echo
echo Bluetooth udev rule.
sleep 1s
mkdir -p /lib/udev/rules.d/
mv -f 99-com.rules /lib/udev/rules.d/99-com.rules
echo Done.

#### Extra firmware
extra_firmware

### Network Setup
if [[ `grep -w "bcm2711" "/root/soc.txt"` ]]; then
	bcm2711_network;
fi
if [[ `grep -w "bcm2710" "/root/soc.txt"` ]]; then
	bcm2710_network;
fi
if [[ `grep -w "bcm2709" "/root/soc.txt"` ]]; then
	bcm2710_network;
fi

### ZSWAP
echo
echo Adjusting zramswap config.
sleep 1s
zramswap_config
echo Done.

### MOTD instructions
echo
echo Adding motd first boot.
sleep 1s
rm -f /etc/motd
mv -f motd /etc/motd
mv -f new.motd /etc/new.motd
chown root:root /etc/motd
chown root:root /etc/new.motd
echo Done.

### Wireless regdb
wireless_regdb

### Adding sys-mods
echo
echo Building raspi-sys-mods package.
sleep 1s
apt update
apt install -y debhelper d-shlibs rfkill dosfstools psmisc
git clone https://github.com/RPi-Distro/raspberrypi-sys-mods.git
cd raspberrypi-sys-mods
dpkg-buildpackage -us -uc
cd ~
dpkg -i raspberrypi-sys-mods*.deb
rm -fdR raspberrypi-sys-mods*
echo Removing vscode repo...
if [ -e /etc/apt/sources.list.d/vscode.list ]; then
	rm -f /etc/apt/sources.list.d/vscode.list;
fi
if [ -e /etc/apt/trusted.gpg.d/microsoft.gpg ]; then
	rm -f /etc/apt/trusted.gpg.d/microsoft.gpg;
fi
if [ -e /etc/apt/preferences.d/3rd_parties.pref ]; then
	rm -f /etc/apt/preferences.d/3rd_parties.pref;
fi
echo Done.

### Pi Bluetooth
pi_bluetooth

###  Adding raspi userland
rpi_userland

### Adding eeprom
if [[ `grep -w "bcm2711" "/root/soc.txt"` ]]; then
	bcm2711_eeprom;
fi

#### Kernel
echo
echo Installing kernel.
apt update
apt upgrade -y
apt -y clean
apt -y autoclean
sleep 1s
cd ~
dpkg -i *.deb
rm -f *.deb
echo Done.
sleep 1s
fetch_version

### Modules
if [[ `grep -w "bcm2711" "/root/soc.txt"` ]]; then
	bcm_modules;
fi
if [[ `grep -w "bcm2710" "/root/soc.txt"` ]]; then
	bcm2710_modules;
fi
if [[ `grep -w "bcm2709" "/root/soc.txt"` ]]; then
	bcm2710_modules;
fi

### Admin or user
if [[ `grep -w "admin=1" "/root/userdata.txt"` ]]; then
	admin_config;
else
	user_config;
fi
if [[ `grep -w "rootpasswd=1" "/root/userdata.txt"` ]]; then
	root_password;
fi

### Clean misc files
rm -f {*.patch,*led*,*eeprom*}

### Vchiq permissions
echo 'SUBSYSTEM=="vchiq",GROUP="video",MODE="0777"' > /etc/udev/rules.d/10-vchiq-permissions.rules
echo 'SUBSYSTEM=="vcio",GROUP="video",MODE="0777"' >> /etc/udev/rules.d/10-vchiq-permissions.rules
echo 'SUBSYSTEM=="vc-mem",GROUP="video",MODE="0777"' >> /etc/udev/rules.d/10-vchiq-permissions.rules

#### Led switches
led_switches

#### First boot service
firstboot_service

#### Credentials service
credentials_service

#### Governor service
governor_service

#### Create RC.LOCAL
echo
echo Creating rc.local file.
sleep 1s
tee /etc/systemd/system/rc-local.service <<EOF
[Unit]
Description=/etc/rc.local
ConditionPathExists=/etc/rc.local

[Service]
Type=forking
ExecStart=/etc/rc.local start
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target
EOF
tee /etc/rc.local <<EOF
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# tmp wlan pwr mngt fix
iwconfig wlan0 power off
exit 0
EOF
chmod +x /etc/rc.local
echo Done.
### Enable services
echo
echo Enabling Services.
sleep 1s
enable_services > /dev/null 2>&1
echo Done.

###### Finish
echo
echo Moving out of stage2 and creating image.
echo
sleep 2s

umount /proc /sys
