#!/bin/bash

INITRD_BRCM="/boot/broadcom/initrd.gz"

if [[ -d "/boot" ]] && [[ `ls  /boot/initrd.img-*` ]] > /dev/null 2>&1; then
	echo "update-initramfs: Generating ${INITRD_BRCM}"
	mkdir -p /boot/broadcom
	rm -fr /boot/{initrd.gz,initrd.img-*-bak}
	rm -fr /boot/broadcom/initrd.gz
	cp -f /boot/initrd.img-* ${INITRD_BRCM}
	rm -f /boot/firmware
	ln -s /boot/broadcom /boot/firmware
fi

exit 0
