#!/bin/bash

COMPRESSION="xz"
PLATFORM="broadcom"
LINUX_IMAGE="linux-image-${SERIES}"
LINUX_HEADERS="linux-headers-${SERIES}"
OVERLAY_PATH="usr/lib/${LINUX_IMAGE}/overlays"
INSTALL_PATH="boot/${PLATFORM}"

linux_packaging(){
# install target
if [[ "$ARCH" == "arm" ]]; then
	LINUX_PATH="usr/lib/${LINUX_IMAGE}"
else
	LINUX_PATH="usr/lib/${LINUX_IMAGE}/${PLATFORM}"
fi
cat <<EOF > "scripts/package/pkgvars"
# packaging variables
board_series="$SERIES"
kernel_img="$KERNEL_IMG"
linux_name="$LINUX_IMAGE"
headers_name="$LINUX_HEADERS"
compression="$COMPRESSION"
linux_path="$LINUX_PATH"
overlays_path="$OVERLAY_PATH"
boot_path="$INSTALL_PATH"
karch="$ARCH"
# host codename
host_codename="$HOST_CODENAME"
EOF
}
